### ISSUE TITLE
Instruction tuning support

### ISSUE THREAD

**Issue by vivekmadan2** [meta-llama/llama-recipes#102]
### 🚀 The feature, motivation and pitch

Is there a plan to add support for (FLAN style) instruction tuning? 

Ideally, we should do summarization (SamSum dataset used in this repo) as instruction tuning as well. For example,  we should not compute loss on the input part.

**Comment by HamidShojanazeri** [comment]
@vivekmadan2 would be interested to send a PR, will be happy to help review and getting it merged.

**Comment by findalexli** [comment]
Any support on this? We found out that the training is doing just next token prediction but I think most folks are doing instruction tuning

**Comment by wukaixingxp** [comment]
Hi! Here is a example of instruction fine-tuning using [samsum dataset](https://github.com/meta-llama/llama-recipes/blob/main/src/llama_recipes/datasets/samsum_dataset.py#L10) where the [input part has been masked out](https://github.com/meta-llama/llama-recipes/blob/raft/src/llama_recipes/datasets/samsum_dataset.py#L32).
