### ISSUE TITLE
Fine-tuning Chat models

### ISSUE THREAD

**Issue by vivekmadan2** [meta-llama/llama-recipes#103]
### 🚀 The feature, motivation and pitch

Is there a plan to support fine-tuning for chat models with recommended settings/datasets/data processors etc?

**Comment by HamidShojanazeri** [comment]
@vivekmadan2 sure, we are planning on this not ETA yet.

**Comment by IamExperimenting** [comment]
@HamidShojanazeri, is fine tuning for chat model available now?

**Comment by HamidShojanazeri** [comment]
I am working on it, hopefully it should be ready in couple of weeks.

**Comment by init27** [comment]
Closing as we have example in fine-tuning recipes. Please re-open if you have any questions!
