### ISSUE TITLE
Inference a new model when finetune Llama-7B with own data

### ISSUE THREAD

**Issue by cong20136985** [meta-llama/llama-recipes#111]
1. I have fine-tuned Llama-7B model using FSDP only like:
`torchrun --nnodes 1 --nproc_per_node 8  llama_finetuning.py --enable_fsdp --model_name /patht_of_model_folder/7B --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --pure_bf16`
2. Dataset that i used has the format like alpaca_dataset (200.000 instruction sample Vietnamese).
3. Then convert my FSDP checkpoint to HuggingFace checkpoints using:
`python inference/checkpoint_converter_fsdp_hf.py --fsdp_checkpoint_path  PATH/to/FSDP/Checkpoints --consolidated_model_path PATH/to/new_model --HF_model_path_or_name PATH/model_7B`
4. Then run inference using:
`python inference/inference.py --model_name <new_model> --prompt_file <test_prompt_file>` 

**But the result returns nothing. Please help me to solve**

**Comment by HamidShojanazeri** [comment]
@cong20136985 can you pls try passing sampling params to the `inference.py` as well, `--top_p 0.9` , `--temperature 0.6`.

**Comment by cong20136985** [comment]
![demo](https://github.com/facebookresearch/llama-recipes/assets/16526846/7e8b852a-d8c7-42d9-8ceb-199d15a2c33e)
I tried with new model
But with old model (convert 7B model to HF model)
![demo2](https://github.com/facebookresearch/llama-recipes/assets/16526846/6e83b4be-6acb-4a04-8213-b4772d4f36f4)
The text was generated is nonsense

**Comment by HamidShojanazeri** [comment]
@cong20136985 seems you are running the chats.json as the prompt/ make a new prompt file. I wonder if for this you are making use of `[chat_completion.py](https://github.com/facebookresearch/llama-recipes/blob/main/inference/chat_completion.py)` or `inference.py` and incase the latter can you pls share a repro( your inference script+ the prompt.json).

**Comment by cong20136985** [comment]
Sure, It's my inference script:
`python inference/chat_completion.py --model_name ./models/7B-chat-convert --prompt_file ./data/test.json --top_p 0.9 --temperature 0.6`
And the _test.json_:
```
[
     [{"role": "user", "content": "Describe a time when you had to make a difficult decision.?"}]
]
```
I dont know why the "model output:" is text of "test.json"

**Comment by HamidShojanazeri** [comment]
It seems be stale, closing this pls feel free to re-open if still seeing the issue.
