### ISSUE TITLE
Is pre-training using same (mixed precision) as fine-tuning?

### ISSUE THREAD

**Issue by haozhouamzn** [meta-llama/llama-recipes#117]
The [fine-tuning script](https://github.com/facebookresearch/llama-recipes/blob/main/configs/training.py#L20-L21) uses BF16+mixed precision. Does the pre-training also use BF16+mixed precision?

**Comment by haozhouamzn** [comment]
> @haozhouamzn its doable but nuanced given your settings for your task. Just note that what is suggested here is mostly around Fine-tuning for now.

@HamidShojanazeri thanks, that make sense. 

So for the original [Llama2 models](https://github.com/facebookresearch/llama), do you know what precision is used for pre-training?

**Comment by kongjiellx** [comment]
is use_kahan_summation better when use bf16 adam?
