### ISSUE TITLE
llama 2 distributed training on AWS Sagemaker

### ISSUE THREAD

**Issue by premanand09** [meta-llama/llama-recipes#130]
Hi,
I am going to do distributed training of llama on aws sagemaker as managed training across multiple devices/nodes. Sagemaker provides data parallel and model parallel distributed training in sagemaker.
SInce sagemaker already takes care of distributed training, do i need to keep current FSDP implementation of llama fine tuning script? or should i remove it?

**Comment by aabayarea** [comment]
a recipe for this would be very helpful

**Comment by premanand09** [comment]
Yes. I need a suggestion here if keeping FSDP implementation makes sense for managed distributed training in sagemaker. Kindly help.

**Comment by gemmert-lab49** [comment]
+1

**Comment by wukaixingxp** [comment]
Hi! I found this [tutorial from Sagemaker](https://github.com/aws/amazon-sagemaker-examples/blob/main/introduction_to_amazon_algorithms/jumpstart-foundation-models/llama-2-finetuning.ipynb), hopefully it can solve this issue.
