### ISSUE TITLE
LORA fine tune on dataset GEM/viggo

### ISSUE THREAD

**Issue by goog** [meta-llama/llama-recipes#132]
### 🚀 The feature, motivation and pitch
I dont think it is a bug, so i put the issue here.  
how should I to fine tune on a dataset like GEM/viggo

```bash
torchrun --nnodes 1 --nproc_per_node 4  ./llama_finetuning.py --enable_fsdp --model_name NousResearch/Llama-2-7b-hf --use_peft --peft_method lora --output_dir PathFT --dataset alpaca_dataset --batch_size_training 8
```
data is https://[huggingface.co/googcheng/7b-viggo/raw/main/file.json](https://huggingface.co/googcheng/7b-viggo/raw/main/file.json)
my config 
```
{
  "auto_mapping": null,
  "base_model_name_or_path": "NousResearch/Llama-2-7b-hf",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "lora_alpha": 32,
  "lora_dropout": 0.05,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 8,
  "revision": null,
  "target_modules": [
    "q_proj",
    "v_proj"
  ],
  "task_type": "CAUSAL_LM"
}
```
but it can't inference the target formatted output data.  
standard full parameter fine-tuning can make it [link](https://www.anyscale.com/blog/fine-tuning-llama-2-a-comprehensive-case-study-for-tailoring-models-to-unique-applications)  
SHOULD I need to add a command like "covert data to attributes" to instruction field of JSON ?

**Comment by HamidShojanazeri** [comment]
@goog as this is a new dataset for this repo, you can follow this [example](https://github.com/facebookresearch/llama-recipes/blob/main/examples/custom_dataset.py) and this [doc](https://github.com/facebookresearch/llama-recipes/blob/main/docs/Dataset.md#using-custom-datasets) to add your new dataset, also if interested feel free to make it a PR if you like to add the dataset here as well.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
