### ISSUE TITLE
Why inference is different with same prompt while using the model just after LORA fine tuning in quickstart notebook and then using the same model with inference.py script

### ISSUE THREAD

**Issue by aaekay** [meta-llama/llama-recipes#134]
I am getting different inference results when i am using two methods but the same model. I want to know how are these two scripts different

1. using quickstart notebook, and fine-tuning using Lora approach, in the end, I am using evaluation to get an inference, and that inference is similar to what i intend to get
2. using inference.py script, the path to the base model and adapter is provided, and the same prompt is used, but inference results are poor.

I am using 13B-chat; what could be the reason for this?

**Comment by HamidShojanazeri** [comment]
@aaekay the inferene script is passing sampling params such as [temperature](https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.py#L28C5-L28C16) and top_p, please make sure you pass the same args to the generate function in notebook as well.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
