### ISSUE TITLE
Finetune LLama-2-70B using 16 * A10 (16 * 24G)GPUs?

### ISSUE THREAD

**Issue by babytdream** [meta-llama/llama-recipes#139]
### 🚀 The feature, motivation and pitch

There are few tutorials on  LLama-2-70B using 16 * A10. Can you give me a command if possible？Thanks!

**Comment by HamidShojanazeri** [comment]
@babytdream  Given that you have a cluster that enable you to get 2 nodes of A10s, you might be able to use the following slurm script and need run the job/ the script from the headnode.

Just I believe if you wan to use A10s you might need PEFT as well, personally haven't run it on A10 yet. In the following script there are some EFA settings, in case your A10 instances are from AWS and some of them support EFA use them otherwise comment them out.

```
#!/bin/bash

#SBATCH --job-name=Nano-2d-trainer-20b-8nodes

#SBATCH --ntasks=2
#SBATCH --nodes=2
#SBATCH --gpus-per-task=8
#SBATCH --partition=train 
nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
# Enable for A100/A10s that support EFA
export FI_PROVIDER="efa"

echo Node IP: $head_node_ip
export LOGLEVEL=INFO
# debugging flags (optional)
export NCCL_DEBUG=WARN
export NCCL_DEBUG_SUBSYS=WARN
export PYTHONFAULTHANDLER=1
export LD_LIBRARY_PATH=/opt/amazon/efa/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
export CUDA_LAUNCH_BLOCKING=0

# on your cluster you might need these:
# set the network interface
export NCCL_SOCKET_IFNAME="ens"
export FI_EFA_USE_DEVICE_RDMA=1

srun  torchrun --nproc_per_node 8 --rdzv_id $RANDOM --rdzv_backend c10d --rdzv_endpoint $head_node_ip:29500 
 llama_finetuning.py --enable_fsdp --low_cpu_fsdp --pure_bf16  --use_peft --peft_method lora  --model_name PATH/TO/70B  --output_dir Path/to/save/PEFT/model 
 
 ```
 
 On the headnode, save the above in `multi-node.slurm` or any name.
 
 - activate your virtual env 
 - sbatch multi-node.slurm

**Comment by babytdream** [comment]
@HamidShojanazeri Hi, I have 16 GPUs in one machine, here is my gpu:
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/af2ce8d8-ad16-4386-9689-582e47825c2f)
Can I run this multi-node.slurm?

I want to ask you another question about inference llama2-70b in 16 GPUs. I can't use this gpus to run  a essay code, like this:
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
tokenizer = AutoTokenizer.from_pretrained("upstage/Llama-2-70b-instruct-v2")
model = AutoModelForCausalLM.from_pretrained(
    "upstage/Llama-2-70b-instruct-v2",
    device_map="auto",
    torch_dtype=torch.float16,
    load_in_8bit=True,
    rope_scaling={"type": "dynamic", "factor": 2} # allows handling of longer inputs
)
prompt = "### User:\nThomas is healthy, but he has to go to the hospital. What could be the reasons?\n\n### Assistant:\n"
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
if "token_type_ids" in inputs:
  del inputs["token_type_ids"]
streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
output = model.generate(**inputs, streamer=streamer, use_cache=True, max_new_tokens=float('inf'))
output_text = tokenizer.decode(output[0], skip_special_tokens=True) 
```
This appears an  error:
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/69052efe-6aa8-4ec0-9446-5f65bda0564d)
I ask many people to solve this problem,but failed.
I know 8 gpu can work it! But I need to increase the prompt of llama2, the 8 GPU is not enough!
Do you have some ideas, thanks!

**Comment by HamidShojanazeri** [comment]
I haven't tried TextStreamer, but can you give it a try to this[ inference.py](https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.py), see if that works?

> Can I run this multi-node.slurm?

In this case if you have one machine you wont need that just the normal [multi-gpu command ](https://github.com/facebookresearch/llama-recipes/blob/main/docs/multi_gpu.md)should help you either with FSDP or FSDP+ PEFT.

**Comment by babytdream** [comment]
@HamidShojanazeri 
Hi, I run it according to your commands, but it failed with the same question.For details, please refer to the answer of this link, thanks.
https://github.com/facebookresearch/llama-recipes/issues/140#issuecomment-1695188919

**Comment by chauhang** [comment]
@babytdream Which cloud are you using for running your tests? Please run the `p2pBandwidthLatencyTest` sample from CUDA example as described in this [post](https://confluence.infn.it/pages/viewpage.action?pageId=89820479) and share the results. 

Also suggest running another test with the latest PyTorch nightlies and CUDA 11.8 or CUDA 12.0 and see if that is working in your setup.

**Comment by babytdream** [comment]
@chauhang 
Hi, my cloud is Alibaba Cloud. These is result:
when run this command:`cuda-samples/Samples/0_Introduction/simpleP2P/simpleP2P`
[log1.txt](https://github.com/facebookresearch/llama-recipes/files/12471426/log1.txt)

when run this command:`cuda-samples/Samples/5_Domain_Specific/p2pBandwidthLatencyTest/p2pBandwidthLatencyTest`
[log2.txt](https://github.com/facebookresearch/llama-recipes/files/12471429/log2.txt)

And this is my cuda and Toolkit:
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/c8854578-c4df-41dc-bb26-a74b0ac3f873)
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/25e20f3a-f025-46b4-a7c5-98fb717c8f75)

**Comment by chauhang** [comment]
@babytdream P2P settings seem to be fine based on the logs. Try setting below environment variables and then run one of the fine-tuning commands for pure FSDP or PEFT + FSDP.  Will be best to try these with the latest PyTorch nightlies: 

```
export CUDA_VISIBLE_DEVICES=0,1,2,3,5,6,7,8,9,10,11,12,13,14,15
export TORCH_DISTRIBUTED_DEBUG=DETAIL
export NCCL_DEBUG=ERROR
```


```

# For FSDP fine-tuning
 torchrun --nnodes 1 --nproc_per_node 16 llama_finetuning.py --enable_fsdp --low_cpu_fsdp --pure_bf16 --model_name meta-llama/Llama-2-70b-hf --num_epochs 1  --dist_checkpoint_root_folder checkpoints --dist_checkpoint_folder fine-tuned

```

```
# For PEFT + FSDP fine-tuning
torchrun --nnodes 1 --nproc_per_node 16  llama_finetuning.py --enable_fsdp --use_peft --peft_method lora --model_name meta-llama/Llama-2-70b-hf --output_dir ./fsdp-models --num_epochs 1 --pure_bf16
```

**Comment by babytdream** [comment]
@chauhang 
Thanks for  your help!Can I ask you another question?
I want to use 16 GPUS  to inference the llama-70b first, and I use this [this](https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.py).
This is my command:`python  inference/inference.py --prompt_file inference/chats.json  --model_name /data/model/Llama-2-70b-chat-hf/`
But it appears same error:
![QQ截图20230830134657](https://github.com/facebookresearch/llama-recipes/assets/74184102/9beac370-ea4a-4288-bada-e0b8b8665d87)

And I try another command:`torchrun --nnodes 1 --nproc_per_node 16 inference/inference.py --prompt_file inference/chats.json  --model_name /data/model/Llama-2-70b-chat-hf/`
But it appears a new error:
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/56461af8-0d2e-487a-a042-70ae2fb34b02)
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/661c89d8-81f2-46c6-a9ad-34eb051d4906)
Did I make any mistakes?Do you have some ideas?Thanks！

**Comment by yanmengxiang1** [comment]
@chauhang I also have the same question when I use 16 GPUS to inference the llama-70b using [inference.py(https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.py](https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.py).
Can you give us some right command to run it? Thanks!

**Comment by chauhang** [comment]
Please see the responses on the inference question issue [here](https://github.com/facebookresearch/llama-recipes/issues/140#issuecomment-1704540777) and use that issue for further follow-ups related to inference.

@babytdream I am assuming you are unblocked for the fine-tuning issue.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
