### ISSUE TITLE
inference the  llama2-70b-chat

### ISSUE THREAD

**Issue by babytdream** [meta-llama/llama-recipes#140]
### System Info

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A10
GPU 1: NVIDIA A10
GPU 2: NVIDIA A10
GPU 3: NVIDIA A10
GPU 4: NVIDIA A10
GPU 5: NVIDIA A10
GPU 6: NVIDIA A10
GPU 7: NVIDIA A10
GPU 8: NVIDIA A10
GPU 9: NVIDIA A10
GPU 10: NVIDIA A10
GPU 11: NVIDIA A10
GPU 12: NVIDIA A10
GPU 13: NVIDIA A10
GPU 14: NVIDIA A10
GPU 15: NVIDIA A10

Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          208
On-line CPU(s) list:             0-207
Thread(s) per core:              2
Core(s) per socket:              26
Socket(s):                       4
NUMA node(s):                    4
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8372HC CPU @ 3.40GHz
Stepping:                        11
Frequency boost:                 enabled
CPU MHz:                         3799.993
CPU max MHz:                     3401.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6800.00
Virtualization:                  VT-x
L1d cache:                       3.3 MiB
L1i cache:                       3.3 MiB
L2 cache:                        104 MiB
L3 cache:                        143 MiB
NUMA node0 CPU(s):               0-25,104-129
NUMA node1 CPU(s):               26-51,130-155
NUMA node2 CPU(s):               52-77,156-181
NUMA node3 CPU(s):               78-103,182-207
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.0.1+cu117
[pip3] torchvision==0.15.2
[conda] cudatoolkit-dev           11.7.0               h1de0b5d_6    conda-forge
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.0.1+cu117              pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### 🐛 Describe the bug

command:CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"  python generate.py --base_model=/data/model/llama2-70b-chat/ --prompt_type=llama2 --use_gpu_id=False --share=True
It appears a BUG when I use GPUs > 10:
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/55b839b4-e2ae-47ae-a752-b1a9a3872b28)

10 gpu is ok！But more gpu is helpful!
When I use GPU <= 10, it can work! Like this command:CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,8,9 python generate.py --base_model=/data/model/llama2-70b-chat/ --prompt_type=llama2 --use_gpu_id=False --share=True
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/e1e04df3-92fe-4d1f-894d-5014e41dd384)

### Error logs

![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/a8172471-07d2-417d-a093-42543bfbcd49)

### Expected behavior

I need  more gpu because longer prompt need more gpu memmory.Thanks!

**Comment by HamidShojanazeri** [comment]
@babytdream can you pls elaborate a bit more and share your `generate.py` script.

**Comment by babytdream** [comment]
@HamidShojanazeri 
The code is very simple.you can see my question in this:
https://github.com/Lightning-AI/lit-gpt/issues/469
Many people think that it need to use FSDP.

This is my simple code(https://huggingface.co/upstage/Llama-2-70b-instruct-v2)：
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
tokenizer = AutoTokenizer.from_pretrained("upstage/Llama-2-70b-instruct-v2")
model = AutoModelForCausalLM.from_pretrained(
    "upstage/Llama-2-70b-instruct-v2",
    device_map="auto",
    torch_dtype=torch.float16,
    load_in_8bit=True,
    rope_scaling={"type": "dynamic", "factor": 2} # allows handling of longer inputs
)
prompt = "### User:\nThomas is healthy, but he has to go to the hospital. What could be the reasons?\n\n### Assistant:\n"
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
if "token_type_ids" in inputs:
  del inputs["token_type_ids"]
streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
output = model.generate(**inputs, streamer=streamer, use_cache=True, max_new_tokens=float('inf'))
output_text = tokenizer.decode(output[0], skip_special_tokens=True)
```
But it apears an error when I use GPUs = 16:
![image](https://github.com/facebookresearch/llama-recipes/assets/74184102/02d48ff0-e5d7-4530-a729-832f7578ac48)
When I use GPUs<=8, it can work.

**Comment by babytdream** [comment]
Nvida say: On non-NVSwitch enabled systems, each device can support a system-wide maximum of eight peer connections.

**Comment by HamidShojanazeri** [comment]
can you pls check this comment. https://github.com/facebookresearch/llama-recipes/issues/139#issuecomment-1694961976

**Comment by HamidShojanazeri** [comment]
@babytdream I am not able to repro it here on my side as I dont have 16 A10 in one machine, otherwise as you mentioned even on 8 GPUs it works fine. Sound more of machine setting issue, but just to make sure can you pls run with PT nightlies and Cuda 11.8 as well?

**Comment by chauhang** [comment]
@babytdream 

Please check that p2pbandwidthlatency tests are working fine on the machine as described [here](https://github.com/facebookresearch/llama-recipes/issues/139#issuecomment-1698419665)

For inference llama-recipes loads the model using [`device_map='auto'`](https://github.com/facebookresearch/llama-recipes/blob/main/inference/model_utils.py#L13) which automatically shards across the GPUs on the machine. If you set the `CUDA_VISIBLE_DEVICES=all` or `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15` it should automatically distribute across the GPUs sepicified. 

You can verify the GPU usage using nvidia-smi or another monitoring tool.

**Comment by babytdream** [comment]
@chauhang I will try your ideas.
And I am currently studying vllm.
Someone have successfully run llama-2-70B by using vllm in 16 * A10. For some reason he didn't tell me how toi do.He only tells me that I need to implement a segmentation plan of more than 8 cards by myself. This is my comand:
`python -m vllm.entrypoints.openai.api_server  --model meta/ llama-2-70B  --tensor-parallel-size=16`
This is the same problem I encountered in the vllm open source community：
`https://github.com/vllm-project/vllm/issues/930#issue-1877152932`

Now I try to modify `vllm/model_executor/models/llama.py `'s sharding strategy.Are you interested in this？

**Comment by chauhang** [comment]
@babytdream Please attach the full logs for your inference tests where you are getting `CUDA Error: peer mapping resource exhausted` error along with the actual commands that you ran. We don't have access to instances with 16 GPUs so difficult to comment without seeing the full logs.

For vLLM you can try the example in the inference folder

`python vLLM_inference.py --model_name  meta-llama/Llama-2-70b-hf tp_size 16 --user_prompt <prompt>`

For TGI try the steps [here](https://github.com/facebookresearch/llama-recipes/tree/main/inference/hf-text-generation-inference#step-1-serving-the-model) by setting num_shard=16

**Comment by babytdream** [comment]
@chauhang 
This is detail:
[2023-09-04 11:34:16,888] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [01:48<00:00,  7.21s/it]
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 32001. This might induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
User prompt deemed safe.
User prompt:
Summarize this dialog:

A: Hi Tom, are you busy tomorrow’s afternoon?

B: I’m pretty sure I am. What’s up?

A: Can you go with me to the animal shelter?.

B: What do you want to do?

A: I want to get a puppy for my son.

B: That will make him so happy.

A: Yeah, we’ve discussed it many times. I think he’s ready now.

B: That’s good. Raising a dog is a tough issue. Like having a baby ;-) 

A: I'll get him one of those little dogs.

B: One that won't grow up too big;-)

A: And eat too much;-))

B: Do you know which one he would like?

A: Oh, yes, I took him there last Monday. He showed me one that he really liked.

B: I bet you had to drag him away.

A: He wanted to take it home right away ;-).

B: I wonder what he'll name it.

A: He said he’d name it after his dead hamster – Lemmy  - he's  a great Motorhead fan :-)))

---

Summary:
Asking to pad to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no padding.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Traceback (most recent call last):
  File "/data/llama-recipes/inference/inference.py", line 139, in <module>
    fire.Fire(main)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/llama-recipes/inference/inference.py", line 107, in main
    outputs = model.generate(
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/transformers/generation/utils.py", line 2724, in sample
    outputs = self(
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 809, in forward
    outputs = self.model(
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 697, in forward
    layer_outputs = decoder_layer(
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/accelerate/hooks.py", line 290, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/accelerate/utils/operations.py", line 160, in send_to_device
    {
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/accelerate/utils/operations.py", line 161, in <dictcomp>
    k: t if k in skip_keys else send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys)
  File "/data/miniconda3/envs/localgpt/lib/python3.10/site-packages/accelerate/utils/operations.py", line 167, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
RuntimeError: CUDA error: peer mapping resources exhausted
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by chauhang** [comment]
Thanks @babytdream Please also attach the output of the p2pbandwithlatencytest

I also suggest opening a ticket with your Cloud Provider if they have actually tested things for all 16 GPUs.  Can they confirm that A10 gpus support P2P for 16 GPUs. 

Nvidia documentation is not very clear around this. See the [here](https://forums.developer.nvidia.com/t/how-can-i-tell-which-nvidia-gpus-will-have-p2p-access-to-the-same-gpu-on-pcie/248378) and [here](https://forums.developer.nvidia.com/t/cuda-peer-resources-error-when-running-on-more-than-8-k80s-aws-p2-16xlarge/45351)

**Comment by babytdream** [comment]
@chauhang Hi, I have test it in https://github.com/facebookresearch/llama-recipes/issues/139#issuecomment-1698438995.
Because some have sucessfully run llama-70b in 16 * A10, I guess it support it.

**Comment by chauhang** [comment]
@babytdream Someone has already responded to these questions on vLLM [forum](https://github.com/vllm-project/vllm/issues/930#issue-1877152932). You may need to switch to higher end GPUs if the use case is related to large context windows. If you have actual proof of anyone getting this working on 16 GPUs please share details.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
