### ISSUE TITLE
Convert the HuggingFace version back to the original LLaMA checkpoint with "xxx.pth" file.

### ISSUE THREAD

**Issue by hduanac** [meta-llama/llama-recipes#141]
Are there any ways to save the model with the HuggingFace version back to the original LLaMA checkpoint ***with "xxx.pth" file***? I tried to use ***torch.save(model.state_dict(), "xxx.pth")*** but the generated "xxx.pth" file is ***different*** from the original LLaMA checkpoint.

**Comment by HamidShojanazeri** [comment]
@hduanac not sure if we have such a converter, you might be able to use the Meta to HF [converter](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py) logics and write your own. The original Meta Llama weights are being saved using FairScale FSDP checkpoints.

**Comment by hduanac** [comment]
> 

Thanks for your response, Hamid. Much appreciated for your suggestions.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
