### ISSUE TITLE
a question about video memory occupancy

### ISSUE THREAD

**Issue by 191220042** [meta-llama/llama-recipes#160]
### 🚀 The feature, motivation and pitch

i follow the instructions like
 python llama_finetuning.py  \
    --use_peft \
    --quantization \
    --model_name "meta-llama/Llama-2-7b-chat-hf" \
    --output_dir Path/to/save/PEFT/model
i wander if i do not use --use_peft(default lora) whether to start full fine-tuning
if so,i found lora and full fine-tuning have the same  video memory occupancy,is this right

**Comment by wukaixingxp** [comment]
Hi! Lora should save some GPU memory than full fine-tuning, please check [this conversation](https://www.reddit.com/r/MachineLearning/comments/15ogvp4/d_how_does_lora_save_memory_footprint_for/) for more details.
