### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data! 

### ISSUE THREAD

**Issue by timothylimyl** [meta-llama/llama-recipes#161]
### System Info

2.0.1+cu118, driver 535.86.05

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

When you run on single GPU, you will encounter this error if you do not quantise. 

To fix this, change this [line](https://github.com/facebookresearch/llama-recipes/blob/main/llama_finetuning.py#L93) from:

```
        model = LlamaForCausalLM.from_pretrained(
            train_config.model_name,
            load_in_8bit=True if train_config.quantization else None,
            device_map="auto" if train_config.quantization else None,
        )
```

to fix:
```
    else:
        model = LlamaForCausalLM.from_pretrained(
            train_config.model_name,
            load_in_8bit=True if train_config.quantization else False,
            device_map="auto", #if train_config.quantization else None,
            torch_dtype=torch.float16,
        )
```

basically, setting the torch_dtype will then I guess load the meta device. 

later on, the loss won't be stable, you will get a lot of `NAN` loss. So I suggest to change it to bf16 in this section:

```
    if train_config.quantization:
        model = prepare_model_for_int8_training(model)
    else:
        model.to(torch.bfloat16)
```

### Error logs

NotImplementedError: Cannot copy out of meta tensor; no data! 

### Expected behavior

Should allow to train on one gpu without quantisation

**Comment by timothylimyl** [comment]
Let me know what you think needs to be in the official changes, I can make a PR.

**Comment by wukaixingxp** [comment]
Hi!  Since our repo has been updated, can you try it again with the latest repo?
