### ISSUE TITLE
Re-train llama2 with unlabeled data

### ISSUE THREAD

**Issue by robinfang7** [meta-llama/llama-recipes#167]
### 🚀 The feature, motivation and pitch

I want to re-train llama2 model with unlabeled data. But I check the prompt is instruction-output format. So, how to retrain llama2 model with raw data. Thx.

**Comment by HamidShojanazeri** [comment]
@robinfang7 in this case you need to use the base model not the chat model, and you might be able to use this [guide](https://huggingface.co/learn/nlp-course/chapter7/6?fw=pt), and then add your custom dataset in this repo, as suggested [here](https://github.com/facebookresearch/llama-recipes/blob/main/docs/Dataset.md#using-custom-datasets) and make use fine-tuning recipes in the repo as it suites you.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
