### ISSUE TITLE
Minimum requirements for llama2-13b and llama2-70b fine-tuning

### ISSUE THREAD

**Issue by batindfa** [meta-llama/llama-recipes#170]
Hello!How many gpu I need for **llama2-13b** and **llama2-70b** to fine-tune ?

**Comment by WuhanMonkey** [comment]
Transferring this to Llama recipe repo where we are a lot of fine tuning examples.

**Comment by wukaixingxp** [comment]
Hi! It seems that the question in the issue has been solved. Closing this issue now but feel free to reopen it if there are more questions.
