### ISSUE TITLE
[Question] How to use llama2 for typical NLP tasks?

### ISSUE THREAD

**Issue by santoshbs** [meta-llama/llama-recipes#175]
I am wondering how we could adapt the example.py files provided to undertake tasks such as:
1. Identify the extent of positive sentiment and negative sentiment in the following text.
2. Detect PERSON names entities and return the result as a json string.

Thanks!
sbs

**Comment by BadrinathMJ** [comment]
@santoshbs I tried to fine tune the dataset it requires the huge GPU and also tried the RAG using Langchain and pinecone. Many Llama-2 model hallucinated for entity extraction. So I think it is necessary to combine fine tuned model with RAG with vector database.

**Comment by wukaixingxp** [comment]
Hi! With the improvement of Llama 3 70B, it should perform well on many NER tasks without any fine-tuning. You can follow this [tutorial](https://medium.com/@grisanti.isidoro/named-entity-recognition-with-llms-extract-conversation-metadata-94d5536178f2) but use Llama3 70B cloud API instead. If you want to fine-tune, you can follow [this tutorial](https://towardsdatascience.com/relation-extraction-with-llama3-models-f8bc41858b9e). Let me know if there are more questions.
