### ISSUE TITLE
Safe tensor support

### ISSUE THREAD

**Issue by raghukiran1224** [meta-llama/llama-recipes#181]
### 🚀 The feature, motivation and pitch

When Hugging Face stores the weights in `safetensors` format, the code will fail to load these and will require the `.bin` files only. This can be an inconvenience or a major issue depending on the environment you work in. Some environments will not even let you load `.bin` because of security settings.

This is fairly easy to support. Adding a flag in the main args and while loading the model, check this flag and provide `use_safetensors` to the constructor will suffice.

### Alternatives

none

**Comment by HamidShojanazeri** [comment]
thanks @raghukiran1224 for the feature request, are you interested in contributing the PR? I would be happy to help review and merge it.

**Comment by raghukiran1224** [comment]
yes, we should be able to do this.. fairly straightforward! Thanks @HamidShojanazeri

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
