### ISSUE TITLE
Runtime error when calling freeze_transformer_layers

### ISSUE THREAD

**Issue by h8907283** [meta-llama/llama-recipes#194]
### System Info

PyTorch version: 2.2.0.dev20230911+cu118
CUDA used to build PyTorch: 11.8
Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

When setting `--freeze_layers`, `freeze_transformer_layers` in `train_utils.py` would get called. The problem is that the function requires 2 parameters.

`def freeze_transformer_layers(model, num_layer):`

But the call in `finetuning.py` only provides 1 parameter, num_layer.

`            freeze_transformer_layers(train_config.num_freeze_layers)`

### Error logs

```
```

### Expected behavior

`--freeze_layers` would work again by adding `model` to the `freeze_transformer_layers` call:

`            freeze_transformer_layers(model, train_config.num_freeze_layers)`

**Comment by h8907283** [comment]
Any update on this? Is it okay if I open a PR? Thanks so much!

**Comment by wukaixingxp** [comment]
Hi! Thanks for bring this up and I think the change has been made to address this [here](https://github.com/meta-llama/llama-recipes/blob/61e85089aede4f8695cfb6e7944526bb7020ee1d/src/llama_recipes/finetuning.py#L175)
