### ISSUE TITLE
[Question] Use load_dataset instead of custom implementation

### ISSUE THREAD

**Issue by Tejaswgupta** [meta-llama/llama-recipes#202]
The alpaca dataset implementation at `src/llama_recipes/datasets/alpaca_dataset.py` loads the data from a json file followed by using a custom implementation to load and tokenize it. Is there any particular reason to not use dataset from HuggingFace directly(tatsu-lab/alpaca).
I am also curious as to how is tokenization in `InstructionDataset. __getitem__` different from `SFTTrainer` and why is `SFTTrainer` not being used altogether.

Thank you for your response.

**Comment by HamidShojanazeri** [comment]
@Tejaswgupta , in this repo, we mostly trying to use PyTorch native APIs, although we have a [notebook](https://github.com/facebookresearch/llama-recipes/blob/main/examples/quickstart.ipynb) with HF trainer (not SFTTrainer). 

On the Alpaca dataset, I wonder if you are interested to make a PR, will be happy to help review and merge it.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
