### ISSUE TITLE
Masking loss from labels associated with user turns

### ISSUE THREAD

**Issue by jveronvialard** [meta-llama/llama-recipes#209]
In `Concatenator.__call__()` https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/datasets/utils.py#L38 labels are created by simply copying the input_ids. Shouldn't the loss from the labels associated with the user turns be masked too? See for example https://github.com/bigcode-project/starcoder/blob/main/chat/dialogues.py#L232 and https://huggingface.co/blog/starchat-alpha#masking-user-labels.

**Comment by mreso** [comment]
Good catch, created a PR

**Comment by jveronvialard** [comment]
Nice, I took a look at the PR https://github.com/facebookresearch/llama-recipes/pull/211, LGTM
