### ISSUE TITLE
FSDP Inference

### ISSUE THREAD

**Issue by TZeng20** [meta-llama/llama-recipes#213]
Hi,

In the inference scripts, I see that there is no option to perform inference with FSDP. 

Is `model.generate` not recommended when it is wrapped in FSDP? Or DDP?

Thanks

**Comment by HamidShojanazeri** [comment]
@TZeng20 yes, inferece with FSDP is not recommended due to the allgather call before each forward pass. Mostly we have explored TGI and VLLM as suggested [here](https://github.com/facebookresearch/llama-recipes/tree/main/examples).

**Comment by hbin0701** [comment]
Hi, I'm also facing this issue.
My models are saved like "__0_0.distcp", "__1_0.distcp"... and so on. How can I load these models so that I can run model.generate?
