### ISSUE TITLE
Run finetuning.py problem with 8 gpus one node , but it's ok with 4 gpus one node

### ISSUE THREAD

**Issue by KIMTAIYONG** [meta-llama/llama-recipes#223]
I run finetuing.py on a node with 8gpus. It works ,  --nproc_per_node 4. 
But run with 8gpus,  --nproc_per_node 8, the error log :
ARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5052 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5055 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 5050) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
llama_finetuning.py FAILED
----------------------------------------------------

nvidia-smi :
[root@host]# nvidia-smi topo -m

        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    CPU Affinity  NUMA Affinity   GPU NUMA ID

GPU0     X      PIX     PIX     PIX     SYS     SYS     SYS     SYS     NODE    NODE    PIX     PIX     SYS     SYS     0-31,64-95    0               N/A

GPU1    PIX      X      PIX     PIX     SYS     SYS     SYS     SYS     NODE    NODE    PIX     PIX     SYS     SYS     0-31,64-95    0               N/A

GPU2    PIX     PIX      X      PIX     SYS     SYS     SYS     SYS     NODE    NODE    PIX     PIX     SYS     SYS     0-31,64-95    0               N/A

GPU3    PIX     PIX     PIX      X      SYS     SYS     SYS     SYS     NODE    NODE    PIX     PIX     SYS     SYS     0-31,64-95    0               N/A

GPU4    SYS     SYS     SYS     SYS      X      PIX     PIX     PIX     SYS     SYS     SYS     SYS     PIX     PIX     32-63,96-127  1               N/A

GPU5    SYS     SYS     SYS     SYS     PIX      X      PIX     PIX     SYS     SYS     SYS     SYS     PIX     PIX     32-63,96-127  1               N/A

GPU6    SYS     SYS     SYS     SYS     PIX     PIX      X      PIX     SYS     SYS     SYS     SYS     PIX     PIX     32-63,96-127  1               N/A

GPU7    SYS     SYS     SYS     SYS     PIX     PIX     PIX      X      SYS     SYS     SYS     SYS     PIX     PIX     32-63,96-127  1               N/A

NIC0    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      PIX     NODE    NODE    SYS     SYS

NIC1    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     PIX      X      NODE    NODE    SYS     SYS

NIC2    PIX     PIX     PIX     PIX     SYS     SYS     SYS     SYS     NODE    NODE     X      PIX     SYS     SYS

NIC3    PIX     PIX     PIX     PIX     SYS     SYS     SYS     SYS     NODE    NODE    PIX      X      SYS     SYS

NIC4    SYS     SYS     SYS     SYS     PIX     PIX     PIX     PIX     SYS     SYS     SYS     SYS      X      PIX

NIC5    SYS     SYS     SYS     SYS     PIX     PIX     PIX     PIX     SYS     SYS     SYS     SYS     PIX      X

**Comment by LMXKO** [comment]
the right command is --nproc_per_node 8，can you show more information

**Comment by KIMTAIYONG** [comment]
root@09e05f797e4a:/dev/llama/llama-recipes-main# torchrun --nnodes 1 --nproc_per_node 8 llama_finetuning.py --enable_fsdp --dataset alpaca_dataset --model_name /dev/llama/7BHF --pure_bf16  --use_peft --peft_method lora --output_dir /dev/llama/save/fsdp/model

WARNING:torch.distributed.run:

*****************************************

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 

*****************************************



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================



===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please run



python -m bitsandbytes



 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}

  warn(msg)

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0

CUDA SETUP: Highest compute capability among GPUs detected: 8.0

CUDA SETUP: Detected CUDA version 117

CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...

Clearing GPU cache for all ranks

--> Running with torch dist debug set to detail

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.86s/it]

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.90s/it]

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.89s/it]

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

--> Model /dev/llama/7BHF



--> /dev/llama/7BHF has 6738.415616 Million params



Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.86s/it]

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.91s/it]

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.91s/it]

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.92s/it]

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.72s/it]

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.

  warnings.warn(

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

bFloat16 enabled for mixed precision - using bfSixteen policy

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

trainable params: 4,194,304 || all params: 6,742,609,920 || trainable%: 0.06220594176090199

--> applying fsdp activation checkpointing...

--> applying fsdp activation checkpointing...

--> Training Set Length = 52002

--> applying fsdp activation checkpointing...

--> applying fsdp activation checkpointing...

--> applying fsdp activation checkpointing...

--> applying fsdp activation checkpointing...

--> Validation Set Length = 200

--> applying fsdp activation checkpointing...

/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

Training Epoch: 0:   0%|                                                                            | 0/1625 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

Training Epoch: 0:   0%|                                                                            | 0/1625 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

Training Epoch: 0:   0%|                                                                            | 0/1625 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

Training Epoch: 0:   0%|                                                                            | 0/1625 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

Training Epoch: 0:   0%|                                                                            | 0/1625 [00:00<?, ?it/s]--> applying fsdp activation checkpointing...

/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.

  warnings.warn(

Training Epoch: 0:   0%|                                                                            | 0/1625 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5059 closing signal SIGTERM

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5062 closing signal SIGTERM

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 5057) of binary: /opt/conda/bin/python

Traceback (most recent call last):

  File "/opt/conda/bin/torchrun", line 33, in <module>

    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper

    return f(*args, **kwargs)

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main

    run(args)

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run

    elastic_launch(

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__

    return launch_agent(self._config, self._entrypoint, list(args))

  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent

    raise ChildFailedError(

torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

====================================================

llama_finetuning.py FAILED

----------------------------------------------------

Failures:

[1]:

  time      : 2023-09-15_08:38:11

  host      : 09e05f797e4a

  rank      : 1 (local_rank: 1)

  exitcode  : -7 (pid: 5058)

  error_file: <N/A>

  traceback : Signal 7 (SIGBUS) received by PID 5058

[2]:

  time      : 2023-09-15_08:38:11

  host      : 09e05f797e4a

  rank      : 3 (local_rank: 3)

  exitcode  : -7 (pid: 5060)

  error_file: <N/A>

  traceback : Signal 7 (SIGBUS) received by PID 5060

[3]:

  time      : 2023-09-15_08:38:11

  host      : 09e05f797e4a

  rank      : 4 (local_rank: 4)

  exitcode  : -7 (pid: 5061)

  error_file: <N/A>

  traceback : Signal 7 (SIGBUS) received by PID 5061

[4]:

  time      : 2023-09-15_08:38:11

  host      : 09e05f797e4a

  rank      : 6 (local_rank: 6)

  exitcode  : -7 (pid: 5063)

  error_file: <N/A>

  traceback : Signal 7 (SIGBUS) received by PID 5063

[5]:

  time      : 2023-09-15_08:38:11

  host      : 09e05f797e4a

  rank      : 7 (local_rank: 7)

  exitcode  : -7 (pid: 5064)

  error_file: <N/A>

  traceback : Signal 7 (SIGBUS) received by PID 5064

----------------------------------------------------

Root Cause (first observed failure):

[0]:

  time      : 2023-09-15_08:38:11

  host      : 09e05f797e4a

  rank      : 0 (local_rank: 0)

  exitcode  : -7 (pid: 5057)

  error_file: <N/A>

  traceback : Signal 7 (SIGBUS) received by PID 5057

====================================================

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
