### ISSUE TITLE
Integrate experiment tracker(s) with llama-recipes

### ISSUE THREAD

**Issue by dushyantbehl** [meta-llama/llama-recipes#225]
### 🚀 The feature, motivation and pitch

We've been utilizing llama-recipes to fine-tune Llama 7B and 13B models for various scenarios and have recognized the need for incorporating a tracking system to monitor our diverse experimental runs. In our repository fork, we've already integrated Aimstack (https://aimstack.io/) as a sample tracker alongside the codebase.

We're now contemplating whether this feature would be welcomed by the broader upstream community. If there is interest from the community, we're more than willing to submit a pull request to this repository.

Our PR will involve a generic tracker API with AIMstack as one of the first modules integrated with the codebase. 

Please let me know your feedback.

**Comment by nairbv** [comment]
cc @chauhang @HamidShojanazeri we're happy to submit a PR, but would like confirmation that aimstack integration would be welcome in this codebase.

I believe we can add it in a way that users without an aimstack account/server wouldn't be affected.

**Comment by dushyantbehl** [comment]
Thanks @HamidShojanazeri we are working on it and will raise it in a few days. Looking forward to it 🙂

**Comment by kiamesdavies** [comment]
@dushyantbehl do you have a sample incorporation of https://aimstack.io/ alongside this codebase

**Comment by dushyantbehl** [comment]
Yes I will share the code in a few days as I had been busy with some work @kiamesdavies 
Sorry for the delay if it is affecting any work.

**Comment by kiamesdavies** [comment]
@dushyantbehl thank you
