### ISSUE TITLE
Finetune LLama-2-70B using the private PCs cluster and GPU (not with AWS cluster and EFA) [4 nodes, 2 GPUs(V100, 32G) per node]

### ISSUE THREAD

**Issue by oliver29520** [meta-llama/llama-recipes#232]
### 🚀 The feature, motivation and pitch

There are few tutorials on LLama-2-70B using the private PCs cluster and GPUs (not with AWS cluster and EFA)to finetune, As I cannot access to AWS cluster and EFA,  there are only some physics PCs and GPUs [ 4 nodes , 2 GPUs(V100, 32G) per node ] on my hands,  could you please give me some solutions to finetune Llama-2-70B if possible？ Thanks!

### Alternatives

None

### Additional context

None

**Comment by HamidShojanazeri** [comment]
@oliver29520 you would not necessarily need EFA to run the 70B, but not sure if running it basically on 8 V100 would be doable that easily given that quantization from bits&bytes is not working with FSDP at this point.  Suggest give it a try to FSDP+PEFT with --low_cpu_fsdp, --purebf16 and --use_fast_kernels ( in your case/ V100 will use memory efficient kernels from Xformers) to see if can make a headway.

**Comment by shaded-blue** [comment]
> @oliver29520 you would not necessarily need EFA to run the 70B, but not sure if running it basically on 8 V100 would be doable that easily given that quantization from bits&bytes is not working with FSDP at this point. Suggest give it a try to FSDP+PEFT with --low_cpu_fsdp, --purebf16 and --use_fast_kernels ( in your case/ V100 will use memory efficient kernels from Xformers) to see if can make a headway.

V100 / Volta does not support BF16, only A100 / Ampere and newer.

**Comment by HamidShojanazeri** [comment]
thats right, one thing to try might be to make sure during loading you add torch_dtype=torch.float16 [here](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/finetuning.py#L96) and `--use_fp16`

**Comment by oliver29520** [comment]
@HamidShojanazeri  Thanks for your answer. if I want to inference with the 70B, can I use 2 V100? if not , how many V100 I need?
The situation is that I have 10 nodes (2 V100 per node), I want inference and finetune 70B, Could you pls give me some solutions?
Can I use  examples/multi_node.slurm ? if I can, I wonder if I need remove
`export FI_PROVIDER="efa" 
export LD_LIBRARY_PATH=/opt/amazon/efa/lib:$LD_LIBRARY_PATH`
because I cannot access to AWS cluster and EFA.

**Comment by HamidShojanazeri** [comment]
@HamidShojanazeri unfortunately that wont work with 2 V100 for 70B inference, in the best scenario, you can make it let say int8 that would take minimum 70GB. The multi-node script wont work inference, its for fine-tuning with FSDP. Also FSDP is not the inference path. Multi-node inference is still under discussions.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
