### ISSUE TITLE
Not sure I have FSDP working properly; any insight on fine-tuning VRAM req's?

### ISSUE THREAD

**Issue by shaded-blue** [meta-llama/llama-recipes#234]
Sorry for the stupid question, I'm not sure why I can't seem to investigate this well, and it's driving me nuts.

I've tried running the example finetuning script on the 7B model, on a local cluster with 8x V100's 16GB's with the example command from the readme: 
`
torchrun --nnodes 1 --nproc_per_node 8 ~/llama2/llama-recipes/examples/finetuning.py --enable_fsdp --pure_bf16 False --use_fp16 True --model_name ~/llama2/llama/llama-2-7b-hf --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint fine-tuned
`

but am going OOM around the time that the Training Epoch's all start showing up:
`
File "/home/dylanhubel/.local/lib/python3.11/site-packages/torch/optim/adamw.py", line 599, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 98.00 MiB. GPU 5 has a total capacty of 15.77 GiB of which 5.12 MiB is free. Including non-PyTorch memory, this process has 15.76 GiB memory in use. Of the allocated memory 13.76 GiB is allocated by PyTorch, and 540.64 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Training Epoch: 0/3, step 0/195 completed (loss: 2.062647819519043):   0%|                                                           | 0/195 [00:11<?, ?it/s]
`

When using PEFT as well, I do get through the first epoch, but go OOM when saving the checkpoints.

Just curious if anyone has any insight on the actual VRAM req's here, I was a little shocked to find the 7B model OOM'ing 128GB of VRAM, full parameter or not.

Thanks for your time, sorry again for what feels like a stupid question.

**Comment by HamidShojanazeri** [comment]
@shaded-blue couple of notes on using FSDP only as you mentioned above, I think you would need `--pure_bf16` the reason is over there we move the whole model into bf16 so it makes it more affordable, whereas in fp16, model is still in fp32 but matrix multiplications happens under amp.autocast. One solution might be to make sure during loading you add torch_dtype=torch.float16 [here](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/finetuning.py#L96), generally believe bf16 would do the work.

on the second note PEFT OOM on checkponiting, can you pls make sure you are. using Pytorch nightlies, the fix for this is available only in nightlies until next release.

**Comment by shaded-blue** [comment]
@HamidShojanazeri thank you for the response!

I am running: 
torch 2.2.0.dev20231005+cu121,
nvidia 535.104.12 + cuda 12.2

I ended up doing a clean install of the system, and am having similar issues.  I actually cannot get PEFT to even begin training now, it just goes OOM; likewise FSDP by itself goes OOM.

I did notice they're capping at about 13gb usage of the gpu's, with only "10gb reserved, 2.5gb reserved but unallocated".  Regardless, if my understanding is correct, when using PEFT and FSDP, even 80gb of VRAM would be sufficient.

I will bring more and better information back this evening when I have access to the machine.

**Comment by shaded-blue** [comment]
Sorry for the delay, here is the output from running:
`torchrun --nnodes 1 --nproc_per_node 8  examples/finetuning.py --enable_fsdp --use_fp16 True --model_name ~/workspace/llama/l2-7b-hf --output_dir ~/workspace/fsdp_output`

[output.txt](https://github.com/facebookresearch/llama-recipes/files/12838768/output.txt)

**Comment by wukaixingxp** [comment]
Hi! Since our repo has been updated, can you retry with our latest main to see if the problem has been solved?
