### ISSUE TITLE
Code Completion and Code Infilling - LLama 7B Inference

### ISSUE THREAD

**Issue by akaneshiro7** [meta-llama/llama-recipes#256]
Hello,

I am trying to run inference for Code LLama using HuggingFace Transformers Accelerate Model for llama 2 7B. I am able to run inference with the examples/inference.py script. However, when I try to run the example command for code completion and code infilling, I get the following error: 

TypeError: llama_forward() got an unexpected keyword argument 'padding_mask'

Warning: The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.

Command:  python examples/code_llama/code_infilling_example.py --model_name ../hf_transformers/7B/ --prompt_file examples/code_llama/code_infilling_prompt.txt  --temperature 0.2 --top_p 0.9

Versions:
torch==2.0.1
transformers==4.34.1
tokenizers==0.14.1
optimum==1.13.2

**Comment by jxmorris12** [comment]
I ran into this issue too. It's supposed to be fixed in the latest update of Transformers: https://github.com/huggingface/optimum/issues/1446

**Comment by HamidShojanazeri** [comment]
thanks @jxmorris12 , @akaneshiro7 seems the fix in optimum should help. Pls let me us know if that works for you.

**Comment by eduardosanchezg** [comment]
Can confirm it works after installing from source.

**Comment by huangyangyu** [comment]
I meet the issue "AttributeError: _hf_hook" too.

**Comment by callumHub** [comment]
It went away when I set 'use_fast_kernels=False'

> I meet the issue "AttributeError: _hf_hook" too.

**Comment by XvHaidong** [comment]
I meet the issue "AttributeError: _hf_hook" too. Could you please fix this? We really want to speed up the inference stage. (With LORA model). Thanks!
