### ISSUE TITLE
ImportError: IProgress not found. Please update jupyter and ipywidgets

### ISSUE THREAD

**Issue by hxue3** [meta-llama/llama-recipes#257]
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[6], line 1
----> 1 model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)

File /usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:2903, in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2893     if dtype_orig is not None:
   2894         torch.set_default_dtype(dtype_orig)
   2896     (
   2897         model,
   2898         missing_keys,
   2899         unexpected_keys,
   2900         mismatched_keys,
   2901         offload_index,
   2902         error_msgs,
-> 2903     ) = cls._load_pretrained_model(
   2904         model,
   2905         state_dict,
   2906         loaded_state_dict_keys,  # XXX: rename?
   2907         resolved_archive_file,
   2908         pretrained_model_name_or_path,
   2909         ignore_mismatched_sizes=ignore_mismatched_sizes,
   2910         sharded_metadata=sharded_metadata,
   2911         _fast_init=_fast_init,
   2912         low_cpu_mem_usage=low_cpu_mem_usage,
   2913         device_map=device_map,
   2914         offload_folder=offload_folder,
   2915         offload_state_dict=offload_state_dict,
   2916         dtype=torch_dtype,
   2917         is_quantized=(load_in_8bit or load_in_4bit),
   2918         keep_in_fp32_modules=keep_in_fp32_modules,
   2919     )
   2921 model.is_loaded_in_4bit = load_in_4bit
   2922 model.is_loaded_in_8bit = load_in_8bit

File /usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:3241, in PreTrainedModel._load_pretrained_model(cls, model, state_dict, loaded_keys, resolved_archive_file, pretrained_model_name_or_path, ignore_mismatched_sizes, sharded_metadata, _fast_init, low_cpu_mem_usage, device_map, offload_folder, offload_state_dict, dtype, is_quantized, keep_in_fp32_modules)
   3238     disk_only_shard_files = []
   3240 if len(resolved_archive_file) > 1:
-> 3241     resolved_archive_file = logging.tqdm(resolved_archive_file, desc="Loading checkpoint shards")
   3242 for shard_file in resolved_archive_file:
   3243     # Skip the load for shards that only contain disk-offloaded weights when using safetensors for the offload.
   3244     if shard_file in disk_only_shard_files:

File /usr/local/lib/python3.10/dist-packages/transformers/utils/logging.py:328, in _tqdm_cls.__call__(self, *args, **kwargs)
    326 def __call__(self, *args, **kwargs):
    327     if _tqdm_active:
--> 328         return tqdm_lib.tqdm(*args, **kwargs)
    329     else:
    330         return EmptyTqdm(*args, **kwargs)

File /usr/local/lib/python3.10/dist-packages/tqdm/notebook.py:242, in tqdm_notebook.__init__(self, *args, **kwargs)
    240 unit_scale = 1 if self.unit_scale is True else self.unit_scale or 1
    241 total = self.total * unit_scale if self.total else self.total
--> 242 self.container = self.status_printer(self.fp, total, self.desc, self.ncols)
    243 self.container.pbar = proxy(self)
    244 self.displayed = False

File /usr/local/lib/python3.10/dist-packages/tqdm/notebook.py:115, in tqdm_notebook.status_printer(_, total, desc, ncols)
    106 # Fallback to text bar if there's no total
    107 # DEPRECATED: replaced with an 'info' style bar
    108 # if not total:
   (...)
    112 
    113 # Prepare IPython progress bar
    114 if IProgress is None:  # #187 #451 #558 #872
--> 115     raise ImportError(
    116         "IProgress not found. Please update jupyter and ipywidgets."
    117         " See [https://ipywidgets.readthedocs.io/en/stable](https://ipywidgets.readthedocs.io/en/stable%3C/span%3E%3Cspan) style="color:rgb(175,0,0)">"
    118         "/user_install.html")
    119 if total:
    120     pbar = IProgress(min=0, max=total)

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
​`

Any idea how to solve this issue

**Comment by HamidShojanazeri** [comment]
@hxue3 can you pls elaborate a bit more what are you trying to run? is it [quick start notebook](https://github.com/facebookresearch/llama-recipes/blob/main/examples/quickstart.ipynb)? seems "ipywidgets" installation is missing, have you install llama-recipe package?

**Comment by hxue3** [comment]
Hi, yes. I tried to run the quick start notebook. I have installed llama-recipe package

**Comment by HamidShojanazeri** [comment]
does installing "ipywidgets" help you?

**Comment by hxue3** [comment]
Not really, I built a docker image with everything included. Here is my Dockerfile if it helps 
```python
FROM nvcr.io/nvidia/pytorch:23.07-py3 AS base

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libx11-6 \
    git \
    curl \
    sudo \
    python3-venv \
    python3-virtualenv \
    python3-pip \
    python-is-python3 && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

#Set Environment variables
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_IGNORE_INSTALLED=0
RUN pip install datasets \
    huggingface-hub \
    loguru \
    lxml \
    matplotlib \
    numpy \
    openpyxl \
    pandas \
    pillow \
    plotly \
    protobuf \
    pyyaml \
    regex \
    tqdm==4.62.2 \
    typing-extensions \
    zipp

WORKDIR ./
COPY ./requirements.txt /usr/local/requirements.txt
RUN ls -l /usr/local/requirements.txt
RUN pip install -r /usr/local/requirements.txt

RUN pip install --extra-index-url https://download.pytorch.org/whl/test/cu118 llama-recipes
ENV MPI=openmpi
``` 

and my requirment.txt is 
```python
torch>=2.0.1
accelerate
appdirs
loralib
bitsandbytes
black
black[jupyter]
datasets
fire
peft
transformers==4.31.0
sentencepiece
py7zr
scipy
optimum
```
