### ISSUE TITLE
OOM when saving model, seems the clause "FSDP(model,...)"  will cause the OOM.

### ISSUE THREAD

**Issue by cyrishe** [meta-llama/llama-recipes#263]
### System Info

A100-40G *8
system ubuntu-20.04
peft                     0.4.0
torch                    2.2.0.dev20231012+cu118

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

After training 34B-codellama2 with LoRA(the training goes on well), OOM when save_pretrained . 
I tried different PEFT versions, from v 0.3.0 to source code, do not work.
It is said PEFT-0.2.0 will work, but llama-recipes can't work with PEFT-0.2.0  

I modified code , added save_pretrained just after model loaded.
It shows that OOM will occur after FSDP operation. 

        mixed_precision_policy, wrapping_policy = get_policies(fsdp_config, rank)
        my_auto_wrapping_policy = fsdp_auto_wrap_policy(model, LlamaDecoderLayer)
        ### add save model before FSDP
        print("before FSDP save model")
        model.save_pretrained("./test_pretrained1")
        model = FSDP(
            model,
            auto_wrap_policy= my_auto_wrapping_policy if train_config.use_peft else wrapping_policy,
            cpu_offload=CPUOffload(offload_params=True) if fsdp_config.fsdp_cpu_offload else None,
            mixed_precision=mixed_precision_policy if not fsdp_config.pure_bf16 else None,
            sharding_strategy=fsdp_config.sharding_strategy,
            device_id=torch.cuda.current_device(),
            limit_all_gathers=True,
            #add use_orig_params=True for adapter#
            #use_orig_params=True,
            sync_module_states=train_config.low_cpu_fsdp,
            param_init_fn=lambda module: module.to_empty(device=torch.device("cuda"), recurse=False)
            if train_config.low_cpu_fsdp and rank != 0 else None,
        )
        ### add save model after FSDP
        print("after FSDP save model")
        model.save_pretrained("./test_pretrained2")

### Error logs

before FSDP save model
trainable params: 19,660,800 || all params: 33,763,631,104 || trainable%: 0.05823070373989121
before FSDP save model
trainable params: 19,660,800 || all params: 33,763,631,104 || trainable%: 0.05823070373989121
before FSDP save model
trainable params: 19,660,800 || all params: 33,763,631,104 || trainable%: 0.05823070373989121
before FSDP save model
^MLoading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]^MLoading checkpoint shards:  14%|█▍        | 1/7 [00:07<00:45,  7.64s/it]^MLoading checkpoint shards:  29%|██▊       | 2/7 [00:14<00:37,  7.48s/it]^MLoading checkpoint shards:  43%|████▎     | 3/7 [00:22<00:29,  7.50s/it]^MLoading checkpoint shards:  57%|█████▋    | 4/7 [00:29<00:22,  7.47s/it]^MLoading checkpoint shards:  71%|███████▏  | 5/7 [00:37<00:15,  7.64s/it]^MLoading checkpoint shards:  86%|████████▌ | 6/7 [00:45<00:07,  7.52s/it]^MLoading checkpoint shards: 100%|██████████| 7/7 [00:52<00:00,  7.42s/it]^MLoading checkpoint shards: 100%|██████████| 7/7 [00:52<00:00,  7.49s/it]
--> Model /mnt/shhg01/cyris/model_hub/codellama34B_chat/

--> /mnt/shhg01/cyris/model_hub/codellama34B_chat/ has 33743.970304 Million params

paras distr: 435 0
LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type='CAUSAL_LM', inference_mode=False, r=16, target_modules=['q_proj', 'v_proj'], lora_alpha=32, lora_dropout=0.05, fan_in_fan_out=False, bias='none', modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None)
trainable params: 19,660,800 || all params: 33,763,631,104 || trainable%: 0.05823070373989121
bFloat16 enabled for mixed precision - using bfSixteen policy
before FSDP save model
after FSDP save model
after FSDP save model
Traceback (most recent call last):
  File "/mnt/shhg01/cyris/univista-llm-train/ft/lora/finetuning.py", line 8, in <module>
Traceback (most recent call last):
  File "/mnt/shhg01/cyris/univista-llm-train/ft/lora/finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "/mnt/shhg01/env/llama-recipes/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    fire.Fire(main)
  File "/mnt/shhg01/env/llama-recipes/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/shhg01/env/llama-recipes/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/shhg01/env/llama-recipes/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/shhg01/env/llama-recipes/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/shhg01/env/llama-recipes/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/shhg01/cyris/univista-llm-train/ft/lora/llama_recipes/finetuning.py", line 204, in main
    component = fn(*varargs, **kwargs)
  File "/mnt/shhg01/cyris/univista-llm-train/ft/lora/llama_recipes/finetuning.py", line 204, in main
    model.save_pretrained("./test_pretrained2")

...
...
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 6 has a total capacty of 39.59 GiB of which 1.12 MiB is free. Process 3377172 has 39.58 GiB memory in use. Of the allocated memory 38.18 GiB is allocated by PyTorch, and 40.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at ../c10/cuda/CUDACachingAllocator.cpp:1114 (most recent call first):

### Expected behavior

I used llama-recipes on finetuning 7B or 13B model,  all went on very well.
But OOM when finetuning 34B, and not in training but in saving. 
Hope we can fix this problem.

**Comment by HamidShojanazeri** [comment]
@cyrishe it seems you are using FSDP only not with PEFT from the code you shared above. Also seems you are trying to save an FSDP wrapped model with mode.save_pretrain(). FSDP checkpoint saving is different and you can find it here, https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/utils/train_utils.py#L155-L174

**Comment by cyrishe** [comment]
@HamidShojanazeri

**Comment by cyrishe** [comment]
@HamidShojanazeri   Thanks for your information. 
I think I am using FSDP and PEFT on the training task.
The training arguments are as follows:
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7  torchrun --nnodes 1 --nproc_per_node 8  finetuning.py  
    --enable_fsdp 
    --pure_bf16 
    --low_cpu_fsdp 
    --use_peft  
    --peft_method lora  
    --batch_size_training 1 
    --gradient_accumulation_steps 4 
    --num_workers_dataloader 4 
    --num_epochs 2 
    --model_name  ${local_path_of_the_weights} 
    --dist_checkpoint_root_folder model_checkpoints 
    --dist_checkpoint_folder fine-tuned 
    --output_dir ${output}

I successfully trained and saved a LoRA adapter for a 7B model, using the same codes, but OOM occurred when I did the same on a 34B model.
Later this week I will train the 7B model again, and record the GPU status when saving the adapter, to see if there will be a boost in mem usage.

**Comment by Mugheeera** [comment]
Hey @cyrishe ,

Did you manage to solve this issue? I am encountering the same problem while trying to finetune 70B with FSDP and PEFT on 5 A100 x 80GB. I successfully managed to train the 7B model before with the same parameters and scripts.

**Comment by yueyugua** [comment]
Hi @HamidShojanazeri , I also got the same OOM error when using 8xH100s.
I'm using the transformer '4.41.0.dev0' and build the llama-recipes from the source.
I observed this error will happen when training with 70B model (in my case, the llama3-70b) and it does not happen for llama 3 8B.
I'm wondering the reason to use use model.save_pretrained when using both PEFT and FSDP instead of using `save_model_and_optimizer_sharded` as did when not using PEFT? (https://github.com/meta-llama/llama-recipes/blob/c1f8de216740712eb0ed21f092c9fb9f47fd74ed/src/llama_recipes/utils/train_utils.py#L228-L259)

Would it possible the reason of OOM is because the model needs to gather weights across ranks before `model.save_pretrained`?

**Comment by HamidShojanazeri** [comment]
@yueyugua the reason for that is if you are trying to FT with Lora then you would need to save only LORA checkpoints which is doable with `model.save_pretrained(train_config.output_dir) ` otherwise, `save_model_checkpoint` will try to save the FSDP checkpoints where it runs into OOM issue.

**Comment by yueyugua** [comment]
Hi @HamidShojanazeri , thank you for the reply. I was using lora to finetune the 70B llama3 model and ran into this OOM issue, that's why I thought this might be the root cause. 

If lora take too much memory, will qlora be the right way to do it? However I found qlora is not supported from this ticket
https://github.com/meta-llama/llama-recipes/issues/240, and I'm wondering is there plan to support it?

**Comment by RoelTim** [comment]
Hi @yueyugua and @HamidShojanazeri , I'm running into the same issue. I'm finetuning llama3-70b with FSDP and Peft Lora on 12xH100 and run into OOM (torch.OutOfMemoryError: CUDA out of memory). The error occurs after the first epoch when trying to save the model `state_dict = model.state_dict()`

My command: `srun torchrun --nnodes=3 --nproc_per_node=4 --rdzv_backend=c10d --rdzv_endpoint=$RDZV_HOST:$RDZV_PORT finetuning.py --model_name "Meta-Llama-3-70B" --dataset custom_dataset --custom_dataset.file my_data.py --low_cpu_fsdp --fsdp_config.pure_bf16 --batch_size_training 1 --enable_fsdp True --fsdp_config.checkpoint_type StateDictType.FULL_STATE_DICT --dist_checkpoint_root_folder --use_peft True --output_dir "model" --save_model True --num_epochs 1 --peft_method lora --use_fp16 --gradient_accumulation_steps 8 --fsdp_config.fsdp_cpu_offload True`

Do you have any suggestions?
