### ISSUE TITLE
I can't find the llama-recipes/ft_datasets  #finetuning custom dataset same as alpaca dataset #

### ISSUE THREAD

**Issue by klyuhang9** [meta-llama/llama-recipes#266]
### System Info

None

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### 🐛 Describe the bug

I looked at tutorials online that taught me how to fine-tuning llama2 , Because I want to fine-tuning on custom dataset. Tutorials say I should download GuanacoDataset/guanaco_non_chat-utf8.json, and change name to alpaca_data.json, and put this data into llama-recipes/ft_datasets  .
After that I just need to run 
`
export CUDA_VISIBLE_DEVICES=1,2,3
torchrun --nnodes 1 --nproc_per_node 3 llama_finetuning.py \
  --enable_fsdp \
  --use_peft \
  --peft_method lora \
  --model_name /home/model_zoo/LLM/llama2/Llama-2-7b-hf/ \
  --dataset alpaca_dataset \
  --pure_bf16 \
  --batch_size_training 50 \
  --num_epochs 2 \
  --output_dir /home/LLM/llama-recipes/PEFT/model`
It stands to reason that this can run normally, but I can't find the corresponding directory ‘llama-recipes/ft_datasets ’ 
I wonder if there is something wrong? Or the old version had this directory before, but now it has been adjusted. Then which directory should I put the custom data(Data in the same format as the alpaca dataset)  set in now? 
Thanks for help~

### Error logs

None

### Expected behavior

None

**Comment by HamidShojanazeri** [comment]
@klyuhang9 can you pls pull the latest code, we dont have llama-recipes/ft_datasets as the result of recent changes. Please let us know if still running into similar issue.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
