### ISSUE TITLE
Add prompts in HelloLlamaLocal Notebook

### ISSUE THREAD

**Issue by weissenbacherpwc** [meta-llama/llama-recipes#267]
Hi,

I followed the 'demo_apps/HelloLlamaLocal.ipynb'-Notebook and everything works fine. Now I want the model to answer in a different language like German, so I need to adjust the prompt. Where in the code to I have to enter my own prompt?

I tried to change the value in 'qa_chain'. However the model keeps anwering in English:
`qa_chain = RetrievalQA.from_chain_type(
    llm(prompt="Bitte Antworte nur auf Deutsch!"),
    retriever=vectordb.as_retriever()`

Thanks in advance!

**Comment by jeffxtang** [comment]
@weissenbacherpwc you can simply append "Give me your answer in German." to the end of your query like the two examples below, using the 7.36GB 13b model:

![image](https://github.com/facebookresearch/llama-recipes/assets/535090/69294c9f-78dd-4cfd-9345-93f05581b09c)

But be aware the 3.82GB 7b model does behave as good as the 13b in terms of giving answer in German. 

Also, the language support for non-English in Llama2 is not as good as English, as stated in the [Llama2 paper](https://arxiv.org/abs/2307.09288):
![image](https://github.com/facebookresearch/llama-recipes/assets/535090/bf11d9bc-39a8-4805-b4da-8a5ee8da5327)

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
