### ISSUE TITLE
how to use checkpoint 

### ISSUE THREAD

**Issue by fireceW** [meta-llama/llama-recipes#273]
### 🚀 The feature, motivation and pitch

I have fine-tuned a model on the 7B pre-trained model, and get the weight files.
![1698400882096](https://github.com/facebookresearch/llama-recipes/assets/113016024/319b1e67-2c1c-437f-b147-de2069841948)
I want to keep fine-tuning,  and What should I do? Do I need to move the files to 7B-hf folder？

**Comment by HamidShojanazeri** [comment]
@fireceW does loading your peft model as follows and continuing tuning work for you?

```
from llama_recipes.inference.model_utils import load_peft_model

 model = load_peft_model(model, peft_model)
 
 ```

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
