### ISSUE TITLE
Quickstart) finetuning kernel version error 

### ISSUE THREAD

**Issue by eunji6546** [meta-llama/llama-recipes#286]
### System Info

PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-4.19.93-1.nbp.el7.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7302 16-Core Processor
Stepping:                        0
CPU MHz:                         3292.930
BogoMIPS:                        5988.83
Virtualization:                  AMD-V
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        16 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-15,32-47
NUMA node1 CPU(s):               16-31,48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.1
[pip3] torch==2.1.0+cu118
[pip3] torch-tb-profiler==0.4.3
[pip3] torchaudio==2.1.0+cu118
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] numpy                     1.26.1                   pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchaudio                2.1.0+cu118              pypi_0    pypi
[conda] torchvision               0.16.0+cu118             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

(I am not yet used to handling LLM Models) 

Hi when I run quickstart.ipynb,
It fails on Step 6: Fine tune the model, at the very early stage of epoch 0 
```python
from transformers import default_data_collator, Trainer, TrainingArguments

# Define training args
training_args = TrainingArguments(
    output_dir=output_dir,
    overwrite_output_dir=True,
    bf16=False,  # Use BF16 if available
    # logging strategies
    logging_dir=f"{output_dir}/logs",
    logging_strategy="steps",
    logging_steps=10,
    save_strategy="no",
    optim="adamw_torch_fused",
    max_steps=total_steps if enable_profiler else -1,
    **{k:v for k,v in config.items() if k != 'lora_config'}
)

with profiler:
    # Create Trainer instance
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        data_collator=default_data_collator,
        callbacks=[profiler_callback] if enable_profiler else [],
    )

    # Start training
    trainer.train()
```

according to warnings
```
Detected kernel version 4.19.93, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
    self._record_writer.write(data)
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 774, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 167, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 172, in _write
    with io.open(filename, mode, encoding=encoding) as f:
FileExistsError: [Errno 17] File exists
...
and error follows below.. 

```
It seems like works done with more than 9 threads, but I can not find where this code produce multi-threadings.
Also, I added `print (filename)` inside `_write` function of `opt/conda/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py` then get two same filename is printed 
```
b'tmp/llama-output/logs/events.out.tfevents.1699255166.test-llama-a100-2-0.37028.4'
b'tmp/llama-output/logs/events.out.tfevents.1699255166.test-llama-a100-2-0.37028.4'
```

### Error logs

---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
Cell In[19], line 31
     22 trainer = Trainer(
     23     model=model,
     24     args=training_args,
   (...)
     27     callbacks=[profiler_callback] if enable_profiler else [],
     28 )
     30 # Start training
---> 31 trainer.train()

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:1591, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1589         hf_hub_utils.enable_progress_bars()
   1590 else:
-> 1591     return inner_training_loop(
   1592         args=args,
   1593         resume_from_checkpoint=resume_from_checkpoint,
   1594         trial=trial,
   1595         ignore_keys_for_eval=ignore_keys_for_eval,
   1596     )

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:1984, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1981     self.state.epoch = epoch + (step + 1 + steps_skipped) / steps_in_epoch
   1982     self.control = self.callback_handler.on_step_end(args, self.state, self.control)
-> 1984     self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
   1985 else:
   1986     self.control = self.callback_handler.on_substep_end(args, self.state, self.control)

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:2314, in Trainer._maybe_log_save_evaluate(self, tr_loss, model, trial, epoch, ignore_keys_for_eval)
   2311     self._globalstep_last_logged = self.state.global_step
   2312     self.store_flos()
-> 2314     self.log(logs)
   2316 metrics = None
   2317 if self.control.should_evaluate:

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:2692, in Trainer.log(self, logs)
   2690 output = {**logs, **{"step": self.state.global_step}}
   2691 self.state.log_history.append(output)
-> 2692 self.control = self.callback_handler.on_log(self.args, self.state, self.control, logs)

File /opt/conda/lib/python3.10/site-packages/transformers/trainer_callback.py:399, in CallbackHandler.on_log(self, args, state, control, logs)
    397 def on_log(self, args: TrainingArguments, state: TrainerState, control: TrainerControl, logs):
    398     control.should_log = False
--> 399     return self.call_event("on_log", args, state, control, logs=logs)

File /opt/conda/lib/python3.10/site-packages/transformers/trainer_callback.py:406, in CallbackHandler.call_event(self, event, args, state, control, **kwargs)
    404 def call_event(self, event, args, state, control, **kwargs):
    405     for callback in self.callbacks:
--> 406         result = getattr(callback, event)(
    407             args,
    408             state,
    409             control,
    410             model=self.model,
    411             tokenizer=self.tokenizer,
    412             optimizer=self.optimizer,
    413             lr_scheduler=self.lr_scheduler,
    414             train_dataloader=self.train_dataloader,
    415             eval_dataloader=self.eval_dataloader,
    416             **kwargs,
    417         )
    418         # A Callback can skip the return of `control` if it doesn't change it.
    419         if result is not None:

File /opt/conda/lib/python3.10/site-packages/transformers/integrations/integration_utils.py:649, in TensorBoardCallback.on_log(self, args, state, control, logs, **kwargs)
    647 for k, v in logs.items():
    648     if isinstance(v, (int, float)):
--> 649         self.tb_writer.add_scalar(k, v, state.global_step)
    650     else:
    651         logger.warning(
    652             "Trainer is attempting to log a value of "
    653             f'"{v}" of type {type(v)} for key "{k}" as a scalar. '
    654             "This invocation of Tensorboard's writer.add_scalar() "
    655             "is incorrect so we dropped this attribute."
    656         )

File /opt/conda/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py:387, in SummaryWriter.add_scalar(self, tag, scalar_value, global_step, walltime, new_style, double_precision)
    382     scalar_value = workspace.FetchBlob(scalar_value)
    384 summary = scalar(
    385     tag, scalar_value, new_style=new_style, double_precision=double_precision
    386 )
--> 387 self._get_file_writer().add_summary(summary, global_step, walltime)

File /opt/conda/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py:109, in FileWriter.add_summary(self, summary, global_step, walltime)
     97 """Adds a `Summary` protocol buffer to the event file.
     98 This method wraps the provided summary in an `Event` protocol buffer
     99 and adds it to the event file.
   (...)
    106     walltime (from time.time()) seconds after epoch
    107 """
    108 event = event_pb2.Event(summary=summary)
--> 109 self.add_event(event, global_step, walltime)

File /opt/conda/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py:94, in FileWriter.add_event(self, event, step, walltime)
     90 if step is not None:
     91     # Make sure step is converted from numpy or other formats
     92     # since protobuf might not convert depending on version
     93     event.step = int(step)
---> 94 self.event_writer.add_event(event)

File /opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py:117, in EventFileWriter.add_event(self, event)
    112 if not isinstance(event, event_pb2.Event):
    113     raise TypeError(
    114         "Expected an event_pb2.Event proto, "
    115         " but got %s" % type(event)
    116     )
--> 117 self._async_writer.write(event.SerializeToString())

File /opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py:171, in _AsyncWriter.write(self, bytestring)
    166 """Enqueue the given bytes to be written asychronously."""
    167 with self._lock:
    168     # Status of the worker should be checked under the lock to avoid
    169     # multiple threads passing the check and then switching just before
    170     # blocking on putting to the queue which might result in a deadlock.
--> 171     self._check_worker_status()
    172     if self._closed:
    173         raise IOError("Writer is closed")

File /opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py:212, in _AsyncWriter._check_worker_status(self)
    210 exception = self._worker.exception
    211 if exception is not None:
--> 212     raise exception

File /opt/conda/lib/python3.10/threading.py:1016, in Thread._bootstrap_inner(self)
   1013     _sys.setprofile(_profile_hook)
   1015 try:
-> 1016     self.run()
   1017 except:
   1018     self._invoke_excepthook(self)

File /opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py:244, in _AsyncWriterThread.run(self)
    242 def run(self):
    243     try:
--> 244         self._run()
    245     except Exception as ex:
    246         self.exception = ex

File /opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py:275, in _AsyncWriterThread._run(self)
    273     if data is self._shutdown_signal:
    274         return
--> 275     self._record_writer.write(data)
    276     self._has_pending_data = True
    277 except queue.Empty:

File /opt/conda/lib/python3.10/site-packages/tensorboard/summary/writer/record_writer.py:40, in RecordWriter.write(self, data)
     38 header_crc = struct.pack("<I", masked_crc32c(header))
     39 footer_crc = struct.pack("<I", masked_crc32c(data))
---> 40 self._writer.write(header + header_crc + data + footer_crc)

File /opt/conda/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py:774, in GFile.write(self, file_content)
    770         self.write_started = True
    772     else:
    773         # append the later chunks
--> 774         self.fs.append(self.filename, file_content, self.binary_mode)
    775 else:
    776     # add to temp file, but wait for flush to write to final filesystem
    777     if self.write_temp is None:

File /opt/conda/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py:167, in LocalFileSystem.append(self, filename, file_content, binary_mode)
    159 def append(self, filename, file_content, binary_mode=False):
    160     """Append string file contents to a file.
    161 
    162     Args:
   (...)
    165         binary_mode: bool, write as binary if True, otherwise text
    166     """
--> 167     self._write(filename, file_content, "ab" if binary_mode else "a")

File /opt/conda/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py:172, in LocalFileSystem._write(self, filename, file_content, mode)
    170 encoding = None if "b" in mode else "utf8"
    171 print (filename) 
--> 172 with io.open(filename, mode, encoding=encoding) as f:
    173     compatify = compat.as_bytes if "b" in mode else compat.as_text
    174     f.write(compatify(file_content))

FileExistsError: [Errno 17] File exists

### Expected behavior

When I run `python -m llama_recipes.finetuning  --use_peft --peft_method lora --quantization --model_name models_hf/7B/ --output_dir ./models_ft/7B/`,[from link](https://github.com/facebookresearch/llama-recipes/blob/main/docs/single_gpu.md)  instead, It works. 

Then, it means there is a lot different using transformers.Trainer(Quickstart notebook) from using llama-recipes.utils.train_utils, or is it really the problem of the kernel version? 

I want to understand the reason why and how to modify quickstart notebook to run successfully.

**Comment by bansky-cl** [comment]
same problem with `Detected kernel version 5.4.267, which is below the recommended minimum of 5.5.0; this can cause the process to hang.`

**Comment by HamidShojanazeri** [comment]
@bansky-cl can you pls elaborate a bit more on the issue? does using single GPU FT recipe work for you? https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/singlegpu_finetuning.md#how-to-run-it

**Comment by bansky-cl** [comment]
> @bansky-cl can you pls elaborate a bit more on the issue? does using single GPU FT recipe work for you? https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/singlegpu_finetuning.md#how-to-run-it

Tks, I change my gpu device make it run successfully.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!

**Comment by eunji6546** [comment]
thanks. I also upgraded my gpu driver and problem solved.
