### ISSUE TITLE
How to evaluate the summarization model performace using Rouge score

### ISSUE THREAD

**Issue by hxue3** [meta-llama/llama-recipes#292]
I was able to replicate the quick start notebook. But I am not sure how to evaluate the fine tuned model's performance. Is there an embedded method for evaluation?

**Comment by HamidShojanazeri** [comment]
@hxue3 it has not been done in the notebook but you should be able to use the same function `get_preprocessed_dataset(tokenizer, samsum_dataset, 'train')` for `validation` and `test` and passing it as `eval_dataset`  to the trainer.
