### ISSUE TITLE
All_reduce fails when data is not available on every process (DDP)

### ISSUE THREAD

**Issue by LeonardoEmili** [meta-llama/llama-recipes#297]
### System Info

PyTorch version: 2.2.0.dev20231111+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.7
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1038-oracle-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-254
Off-line CPU(s) list:            255
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7J13 64-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         2550.000
CPU max MHz:                     3673.0950
CPU min MHz:                     1500.0000
BogoMIPS:                        4900.16
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-254
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.9.16
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20231111+cu118
[pip3] torchaudio==2.2.0.dev20231111+cu118
[pip3] torchdata==0.6.1
[pip3] torchtext==0.15.2+cpu
[pip3] torchvision==0.17.0.dev20231111+cu118
[pip3] triton==2.0.0
[conda] Could not collect

### Information

- [X] The official example scripts
- [X] My own modified scripts

### 🐛 Describe the bug

In some cases, the [reduce operation](https://github.com/facebookresearch/llama-recipes/blob/3b77a270a87b7a8e4084402bd94017d8b88e5458/src/llama_recipes/utils/train_utils.py#L108-L109) for the global gradient computation fails due to the lack of new batches to send to every device. In particular, the bug arises when using small datasets and scaling the per-device batch-size, resulting in some device not performing the forward and backward passes.

**Bug**: when no batches are available, or if the `DistributedSampler` does not select data for every process (DDP), the `all_reduce` is run on an invalid input ([`total_loss`](https://github.com/facebookresearch/llama-recipes/blob/3b77a270a87b7a8e4084402bd94017d8b88e5458/src/llama_recipes/utils/train_utils.py#L73) should be a tensor rather than the scalar 0, otherwise raising a [TypeError](https://github.com/pytorch/pytorch/blob/d00c983b6314483f1050a6b8f127775b59e176f4/torch/distributed/distributed_c10d.py#L840-L845)).
**Solution**: initialize `total_loss` to `torch.tensor([0.0])`

### Error logs

```
File "examples/finetuning.py", line 8, in <module>
  fire.Fire(main)
File "src/llama_recipes/finetuning.py", line 230, in main
  results = train(
File "src/llama_recipes/utils/train_utils.py", line 116, in train
  dist.all_reduce(total_loss, op=dist.ReduceOp.SUM)
File "torch/distributed/distributed_c10d.py", line 844, in _check_single_tensor
  f"Invalid function argument. Expected parameter `{param_name}` to be of type torch.Tensor."

Invalid function argument. Expected parameter `tensor` to be of type to be of type torch.Tensor
```

### Expected behavior

Gradient synchronisation working when multiple devices are used.

**Comment by mariokostelac** [comment]
Doesn't fix it for me. My stacktace:
```
[rank6]:   File "/home/ec2-user/llama-recipes/recipes/finetuning/finetuning.py", line 8, in <module>
[rank6]:     fire.Fire(main)
[rank6]:   File "/home/ec2-user/micromamba/envs/llama-recipes/lib/python3.11/site-packages/fire/core.py", line 143, in Fire
[rank6]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank6]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/ec2-user/micromamba/envs/llama-recipes/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire
[rank6]:     component, remaining_args = _CallAndUpdateTrace(
[rank6]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/ec2-user/micromamba/envs/llama-recipes/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank6]:     component = fn(*varargs, **kwargs)
[rank6]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/ec2-user/llama-recipes/src/llama_recipes/finetuning.py", line 268, in main
[rank6]:     results = train(
[rank6]:               ^^^^^^
[rank6]:   File "/home/ec2-user/llama-recipes/src/llama_recipes/utils/train_utils.py", line 222, in train
[rank6]:     eval_ppl, eval_epoch_loss, temp_val_loss, temp_step_perplexity = evaluation(model, train_config, eval_dataloader, local_rank, tokenizer, wandb_run)
[rank6]:                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/ec2-user/llama-recipes/src/llama_recipes/utils/train_utils.py", line 370, in evaluation
[rank6]:     dist.all_reduce(eval_loss, op=dist.ReduceOp.SUM)
[rank6]:   File "/home/ec2-user/micromamba/envs/llama-recipes/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank6]:     return func(*args, **kwargs)
[rank6]:            ^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/ec2-user/micromamba/envs/llama-recipes/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2195, in all_reduce
[rank6]:     _check_single_tensor(tensor, "tensor")
[rank6]:   File "/home/ec2-user/micromamba/envs/llama-recipes/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 863, in _check_single_tensor
[rank6]:     raise TypeError(
[rank6]: TypeError: Invalid function argument. Expected parameter `tensor` of type torch.Tensor
[rank6]:              but got <class 'float'> instead.
```
