### ISSUE TITLE
Add support to continue pratraining

### ISSUE THREAD

**Issue by hanyin88** [meta-llama/llama-recipes#299]
### 🚀 The feature, motivation and pitch

Currently the LLaMA-receipts do not support pretraining out of box. For example, one could not save the pretrained model based on the current [checkpoint saving logic ](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/utils/train_utils.py#L141-L173) which requires run_validation = True, which is not needed during continued pretraining phase. It would be nice to add this feature down the road as it's a common use case in the process of domain adaption. 

Thanks.

**Comment by thisisisheanesu** [comment]
@hanyin88 Did you find anything for this elsewhere?

**Comment by HamidShojanazeri** [comment]
@hanyin88 the original focus of this repo was about fine-tuning, so it has not been designed to support pertaining, but this is something we are investigating as well.
