### ISSUE TITLE
There's no Demo App Showing How to use LLama with Collab + general questions

### ISSUE THREAD

**Issue by Jaswir** [meta-llama/llama-recipes#310]
### 🚀 The feature, motivation and pitch

Demo app like: 
demo_apps/HelloLlamaLocal.ipynb
demo_apps/HelloLlamaCloud.ipynb

That shows how to setup meta-llama/Llama-2-7b-chat-hf on Google Collab
and ask some basic questions to it.

**Comment by jeffxtang** [comment]
Are you looking for a demo app that shows how to use Llama in Colab? If so, you can just upload the notebook HelloLlamaCloud.ipynb to Colab:

<img width="1114" alt="image" src="https://github.com/facebookresearch/llama-recipes/assets/535090/8e8e25c0-198f-4169-a003-6c62ecf3e3ea">

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
