### ISSUE TITLE
running Fine-tuning using FSDP Only

### ISSUE THREAD

**Issue by Imrancham** [meta-llama/llama-recipes#329]
Hello every one,
I have couple of questions, which might be amature, as I am begginer and not a Linux user.
1. When using CLI e.g., `--use_peft` does it change `use_peft  `to True, or should i make it explicit` --use_peft =True` ?
2. The `model_name` parameter, is it the source model which I wan to fine tune, or it the dir  where I want to save my model? as my saved model appears on dir created at `dist_checkpoint_folder` . If it the case, then how to specify the source model??
3. After fine tuning, spicificly **Fine-tuning using FSDP Only** using: 
`torchrun --nnodes 1 --nproc_per_node 8  examples/finetuning.py --enable_fsdp --model_name /my_saved_hf_model/7B --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned2 --use_fast_kernels
`
then multiple files created at  /model_checkpoints /fine-tuned2 /my_saved_hf_model/7B, including: .distcp fils, .metadata and train_papams.yaml files, my question how to run this model??

Sorry for listing too many questions, and thank you in advanced

**Comment by HamidShojanazeri** [comment]
@Imrancham sorry for late reply, 

re 1: passing `--use_peft` is enough it actually picks as True.

re 2: `--model_name` is the name of the model you want to fine-tune. If you are training with FSDP ONLY then `dist_checkpoint_folder` is the folder where it saves your checkpoints.

re 3: FSDP save the checkpoints in multiple files ( to the number of GPUs you trained the model), to load back the FSDP checkpoints for inference with HF accelerate/ inference code, you can use this guide [here](https://github.com/facebookresearch/llama-recipes/blob/main/docs/inference.md#loading-back-fsdp-checkpoints). Where `llama_recipes.inference.checkpoint_converter_fsdp_hf` basically convert your FSDP Checkpoints to HF format, that you can load it back then.

Please let us know if you have further questions.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
