### ISSUE TITLE
can't run the RAG_Chatbot_Example.ipynb

### ISSUE THREAD

**Issue by monaalsh** [meta-llama/llama-recipes#345]
### System Info

Hello,
I have issues running the RAG_Chatbot_Example.ipynb notebook.
When running the curl command in the notebook, 

`!curl localhost:8080/generate -X POST -H 'Content-Type: application/json' -d '{"inputs": "What is good about Beijing?", "parameters": { "max_new_tokens":64}}' #Replace the locahost with the IP visible to the machine running the notebook     `

I get the following error
```
curl: (6) Could not resolve host: application
curl: (3) URL rejected: Malformed input to a URL function
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched brace in URL position 1:
{
```

I replaced the localhost with the my machine IP which is running the notebook and I'm having Apache HTTP server running in background. What could be wrong to fix this issue?

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Hello,
I have issues running the RAG_Chatbot_Example.ipynb notebook.
When running the curl command in the notebook, 

`!curl localhost:8080/generate -X POST -H 'Content-Type: application/json' -d '{"inputs": "What is good about Beijing?", "parameters": { "max_new_tokens":64}}' #Replace the locahost with the IP visible to the machine running the notebook     `

### Error logs

curl: (6) Could not resolve host: application
curl: (3) URL rejected: Malformed input to a URL function
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched brace in URL position 1:
{

### Expected behavior

The curl command should execute correctly.

**Comment by jeffxtang** [comment]
@monaalsh sorry for the late reply. did you run TGI on your local machine?

Can you try steps [here](https://github.com/facebookresearch/llama-recipes/blob/main/demo_apps/llama-on-prem.md#setting-up-tgi-with-llama-2)?

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
