### ISSUE TITLE
Make predictions based on historical data CSV file?

### ISSUE THREAD

**Issue by marcelooliveira** [meta-llama/llama-recipes#385]
I'd appreciate some advice on a problem, since I don't have expertise in AI or Data Science.

I need to analyze historical data to build a forecasting model, using a CSV data set containing historical data. Then I need to predict future values based on a future date input by the user, using the historical time series present in the dataset.

I'd like to know the model that best suits my training. Does it make sense to base my training on LLama2 or Llama2 chat for this? If not, what's the best model to build upon? And how should I format my historical CSV file?

Thanks in advance!

**Comment by jeffxtang** [comment]
Depending on the characteristics of your historical data, traditional ML models such as regressions, KNN and decision trees (you can use [scikit-learn](https://scikit-learn.org/stable/auto_examples/index.html) to quickly train and test with your data), or neural network models such as RNN and LSTM may be used. Other specialized time series forecasting models such as [Prophet](https://facebook.github.io/prophet/docs/quick_start.html#python-api) can also be used.

LLMs such as Llama 2 may also be used for the forecasting - e.g. see this [repo](https://github.com/ngruver/llmtime).

**Comment by marcelooliveira** [comment]
Hi @jeffxtang, that's nice, I'll look into llmtime repo, Thanks so much for the comprehensive answer!

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
