### ISSUE TITLE
Config updater outputs misleading warnings

### ISSUE THREAD

**Issue by devon-research** [meta-llama/llama-recipes#396]
If I pass an FSDP config flag to `finetuning.py`, as in e.g.

```
torchrun \
    --nproc_per_node 4 \
    llama-recipes/examples/finetuning.py \
        --enable_fsdp \
        --model_name meta-llama/Llama-2-7b-hf \
        --dist_checkpoint_root_folder model_checkpoints \
        --dist_checkpoint_folder fine-tuned \
        --pure_bf16 \
        --use_fast_kernels
```

then in the output I get 

```
Warning: unknown parameter pure_bf16
```

It looks like [the code to update the config](https://github.com/meta-llama/llama-recipes/blob/95418fcabc75114fe86e0d80136f225f0b695886/src/llama_recipes/utils/config_utils.py#L22) has a bug where if a config parameter appears in the FSDP config but not in the training config, it will erroneously output a warning like this.

**Comment by HamidShojanazeri** [comment]
@devon-research can you please [install from src](https://github.com/meta-llama/llama-recipes#install-from-source), it works on my end. BTW we did some refactor recently would be great to [pull the latest first](https://github.com/meta-llama/llama-recipes#llama-recipes-examples-to-get-started-using-the-llama-models-from-meta). Now `lama-recipes/examples/finetuning.py` is changed to `lama-recipes/recipes/finetuning/finetuning.py`

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
