### ISSUE TITLE
running Fine-tuning using FSDP Only but got  FileExistsError

### ISSUE THREAD

**Issue by Matrixxxxxxxx** [meta-llama/llama-recipes#408]
### System Info

my env:
git clone git@github.com:meta-llama/llama-recipes.git
cd /hy-tmp/llama-recipt/llama-recipes-main
pip install -i https://pypi.mirrors.ustc.edu.cn/simple -U pip setuptools
pip install -i https://pypi.mirrors.ustc.edu.cn/simple --extra-index-url https://download.pytorch.org/whl/test/cu118 -e .

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

llama-recipes-main/recipes/finetuning# torchrun --nnodes 1 --nproc_per_node 4  finetuning.py --dataset "custom_dataset" --custom_dataset.file "/hy-tmp/llama-recipt/custom_dataset.py" --enable_fsdp --batch_size_training 4 --num_epochs 1 --model_name /hy-tmp/llama-recipt/llama-2-7b-hf --dist_checkpoint_root_folder /hy-tmp/model_checkpoints --dist_checkpoint_folder ft

### Error logs

Training Epoch: 1/1, step 1/2 completed (loss: 1.8028285503387451): 100%|██████| 2/2 [01:09<00:00, 34.77s/it]
Training Epoch: 1/1, step 1/2 completed (loss: 1.8019635677337646): 100%|██████| 2/2 [01:10<00:00, 35.32s/it]
Training Epoch: 1/1, step 1/2 completed (loss: 1.672827959060669): 100%|███████| 2/2 [01:10<00:00, 35.27s/it]
Training Epoch: 1/1, step 1/2 completed (loss: 1.736147165298462): 100%|███████| 2/2 [01:09<00:00, 34.89s/it]
Max CUDA memory allocated was 31 GB
Max CUDA memory reserved was 40 GB
Peak active CUDA memory was 32 GB
CUDA Malloc retries : 0
CPU Total Peak Memory consumed during the train (max): 1 GB
Epoch 1: train_perplexity=120.2098, train_epoch_loss=4.7892, epoch time 70.22998666507192s
[rank0]: Traceback (most recent call last):
[rank0]:   File "finetuning.py", line 8, in <module>
[rank0]:     fire.Fire(main)
[rank0]:   File "/usr/local/miniconda3/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:   File "/usr/local/miniconda3/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:   File "/usr/local/miniconda3/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:   File "/hy-tmp/llama-recipt/llama-recipes-main/src/llama_recipes/finetuning.py", line 268, in main
[rank0]:     results = train(
[rank0]:   File "/hy-tmp/llama-recipt/llama-recipes-main/src/llama_recipes/utils/train_utils.py", line 259, in train
[rank0]:     save_train_params(train_config, fsdp_config, rank)
[rank0]:   File "/hy-tmp/llama-recipt/llama-recipes-main/src/llama_recipes/utils/train_utils.py", line 468, in save_train_params
[rank0]:     os.makedirs(save_dir)
[rank0]:   File "/usr/local/miniconda3/lib/python3.8/os.py", line 223, in makedirs
[rank0]:     mkdir(name, mode)
[rank0]: FileExistsError: [Errno 17] File exists: '/hy-tmp/model_checkpoints/ft-/hy-tmp/llama-recipt/llama-2-7b-hf'
[rank1]: Traceback (most recent call last):
[rank1]:   File "finetuning.py", line 8, in <module>
[rank1]:     fire.Fire(main)
[rank1]:   File "/usr/local/miniconda3/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:   File "/usr/local/miniconda3/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:   File "/usr/local/miniconda3/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:   File "/hy-tmp/llama-recipt/llama-recipes-main/src/llama_recipes/finetuning.py", line 268, in main
[rank1]:     results = train(
[rank1]:   File "/hy-tmp/llama-recipt/llama-recipes-main/src/llama_recipes/utils/train_utils.py", line 259, in train
[rank1]:     save_train_params(train_config, fsdp_config, rank)
[rank1]:   File "/hy-tmp/llama-recipt/llama-recipes-main/src/llama_recipes/utils/train_utils.py", line 468, in save_train_params
[rank1]:     os.makedirs(save_dir)
[rank1]:   File "/usr/local/miniconda3/lib/python3.8/os.py", line 223, in makedirs
[rank1]:     mkdir(name, mode)
[rank1]: FileExistsError: [Errno 17] File exists: '/hy-tmp/model_checkpoints/ft-/hy-tmp/llama-recipt/llama-2-7b-hf'

### Expected behavior

FSDP save the checkpoints in multiple files.
Each thread write one part of files right? but why got this error?

**Comment by Matrixxxxxxxx** [comment]
Another question is that after training, the only file I got is "train_params.yaml". So where is my weight tensor files?

**Comment by Matrixxxxxxxx** [comment]
And when I change training parameters of "-- batch_size_training 4 --num_epochs 1" in "torchrun --nnodes 1 --nproc_per_node 4  finetuning.py --enable_fsdp...", it seems doesn't work...

**Comment by Matrixxxxxxxx** [comment]
Training Epoch: 1/1, step 1/2 completed (loss: 1.9321104288101196): 100%|██| 2/2 [01:09<00:00, 34.51s/it]

Max CUDA memory allocated was 18 GB
Max CUDA memory reserved was 23 GB
Peak active CUDA memory was 20 GB
CUDA Malloc retries : 0
CPU Total Peak Memory consumed during the train (max): 1 GB
Epoch 1: train_perplexity=202.6627, train_epoch_loss=5.3115, epoch time 73.17671618517488s
training params are saved in /hy-tmp/model_checkpoints/fine-tuned-/hy-tmp/llama-recipt/llama-2-7b-hf/train_params.yaml
Key: avg_train_prep, Value: 202.66268920898438
Key: avg_train_loss, Value: 5.311542987823486
Key: avg_epoch_time, Value: 73.17671618517488
Key: avg_checkpoint_time, Value: 0


As you can see, it just saved params but did not saved the checkpoints

**Comment by HamidShojanazeri** [comment]
@Matrixxxxxxxx yes, FSDP save the checkpoints in multiple files/ each file per rank/ number of GPUs, it should save the checkpoints here `--dist_checkpoint_root_folder /hy-tmp/model_checkpoints --dist_checkpoint_folder ft`  basically `dist_checkpoint_root_folder/dist_checkpoint_folder`.

from the error logs it seems you are trying to overwrite existing checkpoints, make sure to pass a new PATH to save checkpoints. 

```
[rank0]: FileExistsError: [Errno 17] File exists: '/hy-tmp/model_checkpoints/ft-/hy-tmp/llama-recipt/llama-2-7b-hf'
```

can you pls make sure [save_mode](https://github.com/meta-llama/llama-recipes/blob/main/src/llama_recipes/configs/training.py#L36)l is enabled and look in the path you set for ``dist_checkpoint_root_folder/dist_checkpoint_folder`. it should be saved there.

**Comment by Matrixxxxxxxx** [comment]
@HamidShojanazeri checked parameter yaml file, "save_model" is enabled. thanks you and I will continue to pay attention to this issue and related https://github.com/meta-llama/llama-recipes/issues/410
