### ISSUE TITLE
lm_eval.utils

### ISSUE THREAD

**Issue by ZHANGJINKUI** [meta-llama/llama-recipes#421]
### System Info

路径错误

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

from lm_eval.utils import make_table改为from lm_eval.evaluator import make_table路径

### Error logs

from lm_eval.utils import make_table改为from lm_eval.evaluator import make_table路径

### Expected behavior

from lm_eval.utils import make_table改为from lm_eval.evaluator import make_table路径

**Comment by mreso** [comment]
Hi @ZHANGJINKUI 

please update your lm_eval installation to the latest version.

Feel free to reopen if you have further questions.
