### ISSUE TITLE
peft库导入问题

### ISSUE THREAD

**Issue by yimisiyang** [meta-llama/llama-recipes#435]
### System Info

Pytorch 2.1.2+cu12.1, Linux系统，peft=0.10.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### PEFT 库问题

在使用 pip install llama-recipes后，由于最新版本peft=0.10.0 中 `prepare_model_for_int8_training` 方法已经不存在了，取而代之的是 `prepare_model_for_kbit_training` ,因此需要修改 `/anaconda3/envs/llama2/lib/python3.11/site-packages/llama_recipes/finetuning.py` 中有关 `prepare_model_for_int8_training` 的内容，否则会报错。

### Error logs

```
File "/data/cxk_home/llama2/llama-recipes/recipes/finetuning/finetuning.py", line 5, in <module>
    from llama_recipes.finetuning import main
  File "/home/jszx-02/anaconda3/envs/llama2/lib/python3.11/site-packages/llama_recipes/finetuning.py", line 11, in <module>
    from peft import get_peft_model, prepare_model_for_int8_training
ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft' (/home/jszx-02/anaconda3/envs/llama2/lib/python3.11/site-packages/peft/__init__.py)

```

### Expected behavior

将finetuning.py 中的两处 `prepare_model_for_int8_training` 内容改为 `prepare_model_for_kbit_training` 就可以实现正常微调。

**Comment by Karliz24** [comment]
Excelente
Karliz garcia

**Comment by HamidShojanazeri** [comment]
@yimisiyang if you install from src that should work that has[ been added recently.](https://github.com/meta-llama/llama-recipes/blob/main/src/llama_recipes/finetuning.py#L11)
