### ISSUE TITLE
Loading model checkpoints from full parameter tuning

### ISSUE THREAD

**Issue by bkhanal-11** [meta-llama/llama-recipes#436]
Thank you for your attention.

With help from #420, I was able to run full parameter finetuning without making use of the PEFT method as instructed [here](https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/multigpu_finetuning.md). However after training I got model checkpoints and not sure how to load them for inference or evaluation. I have the following files after training:

```bash
.
├── __0_0.distcp
├── __1_0.distcp
├── optimizer-0.pt
└── train_params.yaml

```

I would appreciate it if someone could guide me with this as I am using `AutoModelForCausalLM.from_pretrained()` for loading the model for inference when using base Llama2-7b.

Note: My training code is as follow:
```bash
torchrun --nnodes 1 --nproc_per_node 2  finetuning.py --enable_fsdp --model_name llama-2-7b-hf --dist_checkpoint_root_folder model_checkpoints --use_fast_kernels --output_dir finetuned_models/base_model --save_metrics
```

**Comment by HamidShojanazeri** [comment]
@bkhanal-11 you would need to use this [script to convert you FSDP checkpoints](https://github.com/meta-llama/llama-recipes/blob/d0d36d21be39e300963123dbb37efe4639468c9c/src/llama_recipes/inference/checkpoint_converter_fsdp_hf.py) back to HF format, then you can use HF AutoModel to load back.

Please let us know if that works for you.

**Comment by bkhanal-11** [comment]
@HamidShojanazeri Thank you for your response. This worked fine. Also cheers for the new llama3 models.
