### ISSUE TITLE
freezing layers have differenct behaves for different models

### ISSUE THREAD

**Issue by hjc3613** [meta-llama/llama-recipes#438]
### System Info

Dockerfile: 
![image](https://github.com/meta-llama/llama-recipes/assets/37894838/5597778d-23b0-49ae-9e9a-05563d38a771)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

when freezing the top n layers, it has different effect for different models:
for qwen, the freezed layers has no gradients, so the gpu ram becomes lower contrast to none freezing.
but for qwen1.5 and wizard-8x22B, the freezed layers seemes to have gradients, so the gpu ram still high, even when I freeze top n-1 layers and fintune the last one layer, it gives me OOM when trained on 3 nodes(total 24* A800). 

### Error logs

cuda out of memoy

### Expected behavior

can freeze top layers for any models

**Comment by HamidShojanazeri** [comment]
@hjc3613 sorry for the inconvenience, this feature is not well tested thats why we didn't mention it much. If you are interested, would love to work with you and make a PR to fix the issues.

**Comment by hjc3613** [comment]
> @hjc3613 sorry for the inconvenience, this feature is not well tested thats why we didn't mention it much. If you are interested, would love to work with you and make a PR to fix the issues.

I think this feature is necessary, it can save much gpu memory and get the same results as full parameter training in some practical. I have test in my task that when freeze top 40 layers(total 80 layers), the test results between none freeze are same！！but only use 1 nodes(8*80G)

**Comment by init27** [comment]
@hjc3613 please let us know if you would be interested in contributing with a PR! 

For now, I will close the issue since its not on the current roadmap
