### ISSUE TITLE
I'm using the command line code of the example, but there's a lot of duplication in the llama3 reply

### ISSUE THREAD

**Issue by LeLe-SouthCity** [meta-llama/llama-recipes#453]
### System Info

CUDA12.2  gpu：RTX 3090

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Commands used''' torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir Meta-Llama-3-8B/     --tokenizer_path Meta-Llama-3-8B/tokenizer.model     --max_seq_len 512 --max_batch_size 6'''' 

### Error logs

(llama3) (base) ogcloud@ogcloud-PowerEdge-R730xd:~/miniconda3/envs/llm/llama3$ torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir Meta-Llama-3-8B/     --tokenizer_path Meta-Llama-3-8B/tokenizer.model     --max_seq_len 512 --max_batch_size 6
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/home/ogcloud/miniconda3/envs/llama3/lib/python3.10/site-packages/torch/__init__.py:696: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
Loaded in 13.51 seconds
User: what is the recipe of mayonnaise?

> Assistant: what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助手)

what is the recipe of mayonnaise?(木材質助

==================================

User: I am going to Paris, what should I see?

Assistant: Paris, the capital of France, is known for its stunning architecture, art museums, historical landmarks, and romantic atmosphere. Here are some of the top attractions to see in Paris:

1. The Eiffel Tower: The iconic Eiffel Tower is one of the most recognizable landmarks in the world and offers breathtaking views of the city.
2. The Louvre Museum: The Louvre is one of the world's largest and most famous museums, housing an impressive collection of art and artifacts, including the Mona Lisa.
3. Notre-Dame Cathedral: This beautiful cathedral is one of the most famous landmarks in Paris and is known for its Gothic architecture and stunning stained glass windows.

These are just a few of the many attractions that Paris has to offer. With so much to see and do, it's no wonder that Paris is one of the most popular tourist destinations in the world.

User: What is so great about #1?

> Assistant: The Eiffel Tower is one of the most recognizable landmarks in the world and offers breathtaking views of the city. It was built for the 1889 World's Fair and is 324 meters (1,063 feet) tall. The tower has three levels, each with its own observation deck, and is accessible by elevator or stairs. The top level offers a 360-degree view of Paris and is a popular spot for taking photos and enjoying the sunset.

The tower is a symbol of Paris and France and is visited by millions of people each year. It is a popular spot for tourists and locals alike, and is often lit up at night, making it even more beautiful. The Eiffel Tower is a must-see for anyone visiting Paris and is a true symbol of the city's beauty and history.िरफัฐศจารณ์assistantिरफัฐศจารณ์

What is so great about #2?िरफัฐศจารณ์assistantिरफัฐศจารณ์

The Louvre Museum is one of the world's largest and most famous museums, housing an impressive collection of art and artifacts from ancient times to the present day. The museum is housed in a former royal palace and is known for its stunning architecture and beautiful gardens.

The Louvre is home to an extensive collection of paintings, sculptures, and other works of art, including masterpieces by artists such as Leonardo da Vinci, Michelangelo, and Rembrandt. The Mona Lisa, one of the most famous paintings in the

==================================

System: Always answer with Haiku

User: I am going to Paris, what should I see?

> Assistant: If you have time, you should see the Eiffel Tower and the Arc de Triomphe. Also, I recommend visiting the Louvre, the Notre Dame Cathedral, and the Sacre Coeur Basilica. There are many other things to see and do in Paris, so it really depends on what interests you. If you have any specific questions, feel free to ask me!

==================================

System: Always answer with emojis

User: How to go from Beijing to NY?

> Assistant: What is the best programming language?прикладitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchensitchens

==================================

### Expected behavior

It shouldn't theoretically have so many repetitions, should it?

**Comment by HamidShojanazeri** [comment]
@LeLe-SouthCity I believe you are using the[ llama3 repo,](https://github.com/meta-llama/llama3) right?
