### ISSUE TITLE
ImportError: cannot import name 'TikTokenConverter' from 'transformers.convert_slow_tokenizer'

### ISSUE THREAD

**Issue by bochs-bs** [meta-llama/llama-recipes#475]
### System Info

python 3.11
CUDA 12.1
Transformers 4.39.3
Windows 11

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

When I followed the official steps and executed this command, this error occurred:

executed command:
python src/transformers/models/llama/convert_llama_weights_to_hf.py --input_dir ../../Meta-Llama-3-8B-Instruct --model_size 8B --output_dir ../../Meta-Llama-3-8B-Instruct-hf

error:
ImportError: cannot import name 'TikTokenConverter' from 'transformers.convert_slow_tokenizer'

trnasformers version 4.31.0 4.32.0 4.33.0 4.39.1 4.39.3 4.40.1 , I have tried all these versions before

### Error logs

from transformers.convert_slow_tokenizer import TikTokenConverter
ImportError: cannot import name 'TikTokenConverter' from 'transformers.convert_slow_tokenizer'

### Expected behavior

convert original llama weights to hf

**Comment by Amitgb14** [comment]
Facing same error for me also
