### ISSUE TITLE
llama3 on prem benchmarks

### ISSUE THREAD

**Issue by ifelsefi** [meta-llama/llama-recipes#490]
### 🚀 The feature, motivation and pitch

Documentation and [examples](https://github.com/meta-llama/llama-recipes/tree/main/recipes/benchmarks/inference_throughput/on-prem) are for llama2 benchmarks.   We would like to run llama3 on prem benchmarks.

**Comment by wukaixingxp** [comment]
Hi! I will update the code soon, meanwhile you can change the [MODEL_PATH](https://github.com/meta-llama/llama-recipes/blob/chatbot-e2e/recipes/benchmarks/inference_throughput/on-prem/vllm/parameters.json#L4) to meta-llama/Meta-Llama-3-70B, then launch two vllm servers that host meta-llama/Meta-Llama-3-70B by `CUDA_VISIBLE_DEVICES=0,1,2,3 python -m vllm.entrypoints.openai.api_server  --model meta-llama/Meta-Llama-3-70B --tensor-parallel-size 4 --disable-log-requests --port 8000 
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m vllm.entrypoints.openai.api_server  --model meta-llama/Meta-Llama-3-70B --tensor-parallel-size 4 --disable-log-requests --port 8001 `. You can still use the [chat_vllm_benchmark.py](https://github.com/meta-llama/llama-recipes/blob/chatbot-e2e/recipes/benchmarks/inference_throughput/on-prem/vllm/chat_vllm_benchmark.py) to benchmark.

**Comment by wukaixingxp** [comment]
PR merged, please try the latest example. Let me know if there is any problem.

**Comment by wukaixingxp** [comment]
Closing this issue as the PR has been merged. Let me know if there is any problem!
