### ISSUE TITLE
Finetuning general LLM models from hugging face

### ISSUE THREAD

**Issue by bkhanal-11** [meta-llama/llama-recipes#521]
Thank you for your continuous support to the LLM open-source community.

I was wondering if we use `AutoModel`, `AutoConfig` and `AutoTokenizer` instead of `LlamaForCausalLM`, `LlamaConfig` and `LlamaTokenizer` for general LLM fine-tuning, will the fine-tuning pipeline/recipe fail?

**Comment by mreso** [comment]
Hi @bkhanal-11 for the single gpu use case this might work, but for the advances use cases with FSDP you'll need to [different wrapping policy](https://github.com/meta-llama/llama-recipes/blob/182885ebcddb8ea517bf511194bb1a7f4633d804/src/llama_recipes/policies/wrapping.py#L29) and there might be other things to consider and adapt.

**Comment by bkhanal-11** [comment]
That makes sense, thanks.
