### ISSUE TITLE
no distributed view in tensorboard

### ISSUE THREAD

**Issue by ltm920716** [meta-llama/llama-recipes#533]
### System Info

torch=2.1.2
torch-tb-profilier==0.4.3
cuda=11.8

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

hihi，
    today I test the ‘Multiple GPUs one node’ part with 2 rtx4090 on one node，and I set the ‘--use_profilier’ parameter，but there is not ‘distributed’ view in tensorboard，I cannot find the reason，help please，thanks！

### Error logs

no error，but missing distributed view in tensorboard

### Expected behavior

show distributed view by torch.profilier in tensorboard

**Comment by wukaixingxp** [comment]
Hi! Can you share your command for this task? Did you see two workers in the profiler results? Can you share some screenshots? This may be a Pytorch Profiler with Tensorboard issue mentioned [here](https://github.com/pytorch/kineto/issues/782).

**Comment by ltm920716** [comment]
hello @wukaixingxp,  
  thanks for your reply!

commond:
```
torchrun --nnodes 1 --nproc_per_node 2 ./recipes/finetuning/finetuning.py --enable_fsdp --model_name ../models/Meta-Llama-3-8B-Instruct --batch_size_training 1 --use_peft --peft_method lora --dataset alpaca_dataset --save_model --low_cpu_fsdp --dist_checkpoint_root_folder model_checkpoints21 --dist_checkpoint_folder fine-tuned --pure_bf16  --output_dir fsdp_run21 --use_profiler --profiler_dir profiler21
```

and tensorboard screenshots:
![Screenshot from 2024-05-22 09-54-09](https://github.com/meta-llama/llama-recipes/assets/12007227/8ba5882c-0e24-41fb-91a5-9818ff0ed5bd)
![Screenshot from 2024-05-22 09-56-23](https://github.com/meta-llama/llama-recipes/assets/12007227/549b78e4-d40d-4a7d-ba86-4b59e4c7f424)

there is no distributed view, by the way there is no 'model_checkpoints21' dir in my current workpath by --dist_checkpoint_root_folder

**Comment by init27** [comment]
Closing since the issue discussion is linked above-please reopen if you have any questions or new comments. Thanks!
