### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model

### ISSUE THREAD

**Issue by biaoyanf** [meta-llama/llama-recipes#537]
Hi, 

I was using llama recipe [local inference](https://github.com/meta-llama/llama-recipes/tree/main/recipes/inference/local_inference). 
But I get the warning: 

`Token indices sequence length is longer than the specified maximum sequence length for this model (1998 > 512). Running this sequence through the model will result in indexing errors`

I thought the default token length was 4096 but it seems to be 512. Any idea how to explicitly set it to 4096? 

Thanks.

**Comment by init27** [comment]
Hi @biaoyanf 

Could you kindly try with the updated repo and 3.1 models(s) please?

Let me know if you run into any issues
