### ISSUE TITLE
model name llama2-70b-4096 defined in Getting_to_know_Llama.ipynb doesn't exist in groq anymore

### ISSUE THREAD

**Issue by jarvisDang** [meta-llama/llama-recipes#541]
### System Info

PyTorch version: 2.3.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

model name llama2-70b-4096 defined in Getting_to_know_Llama.ipynb doesn't exist in groq anymore

### Error logs

NotFoundError: Error code: 404 - {'error': {'message': 'The model `llama2-70b-4096` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'code': 'model_not_found'}}
![limits](https://github.com/meta-llama/llama-recipes/assets/35684274/f314a2ce-532b-49df-9d92-b4c724ae9508)

### Expected behavior

model llama2-70b-4096 invoked from groq should be succeeded.

**Comment by ailabby** [comment]
Thanks for creating the issue. Will update the notebook soon. For now, if you need to compare Llama 2 with Llama 3, you may use [Replicate's](https://replicate.com/search?query=llama) models, and this is an [example](https://github.com/meta-llama/llama-recipes/blob/main/recipes/use_cases/VideoSummary.ipynb) of using Replicate.
