### ISSUE TITLE
Add in the use of iterable datasets when fine tuning

### ISSUE THREAD

**Issue by BaiqingL** [meta-llama/llama-recipes#565]
### 🚀 The feature, motivation and pitch

Some datasets may be too large to fit into memory directly, would be nice to provide the option to create an iterable dataset to be passed into the data loader instead of the current hard coded dataset class.

**Comment by HamidShojanazeri** [comment]
thanks @BaiqingL its a good call, will plan it, at the same time pls let me know if you are interested in having a PR.

**Comment by init27** [comment]
@BaiqingL closing the issue for now-but please let us know if you would still be interested in sending a PR! Would love to help and collaborate. 

Thanks!
