### ISSUE TITLE
> Mám malé bitcoiny a mohu zkontrolovat etherscan, ale jak to, že všechny mé peněženky jsou stále prázdné? co mám dělat?

### ISSUE THREAD

**Issue by Karliz24** [meta-llama/llama-recipes#566]
> Mám malé bitcoiny a mohu zkontrolovat etherscan, ale jak to, že všechny mé peněženky jsou stále prázdné? co mám dělat?

_Publicación original de @Tomasmajda en https://github.com/bitcoin-portal/bitcoincom-solidity-swap/pull/9#issuecomment-1349648263_

**Comment by wukaixingxp** [comment]
Hi! It seems that this issue is not related to anything in Llama space, it will be closed.
