### ISSUE TITLE
find bugs in langgraph-rag-agent.ipynb

### ISSUE THREAD

**Issue by jarvisDang** [meta-llama/llama-recipes#571]
### System Info

no gpu needed,  common cpu can run this jupter note

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

bug1:  function format_docs is declared but never used, it should be used to convert Document to String
bug2:  in class GraphState,     documents : List[str] should be declared as documents : List[Document]
I submit a pull request to solve these 2 bugs , plz refer to my pull request and pass it:  https://github.com/meta-llama/llama-recipes/pull/570

### Error logs

no comiling error log

### Expected behavior

no comiling error log, just code correction

**Comment by wukaixingxp** [comment]
@jeffxtang Can you take a look at this issue and the PR 570. Thanks!

**Comment by jeffxtang** [comment]
Thanks @jarvisDang @wukaixingxp PR looks good and merged.
