### ISSUE TITLE
What's the motivation of sorting dataset by length?

### ISSUE THREAD

**Issue by Ber666** [meta-llama/llama-recipes#574]
Hi, thanks for this amazing repo.

In some settings the dataset will by sampled by LengthBasedBatchSampler ([code](https://github.com/meta-llama/llama-recipes/blob/a29ae75286de4d83ceeecca685de61532bf4064d/src/llama_recipes/data/sampler.py#L23)). Could you explain why it's desirable to sort the data according to the length of the first key?

Thanks!

**Comment by Ber666** [comment]
If I understand correctly, it's just to prevent dataset order inconsistency across different devices, caused by the randomness in data preprocessing. So, if the data preprocessing is deterministic, there is no need to sort. Is that correct?

**Comment by wukaixingxp** [comment]
Hi! I believe sorting may reduce the need of padding and optional packing and eventually can speed up the training. For more detail you can read [this post](https://medium.com/@timothylimyonglee/finetuning-llm-efficiently-part-2-sorting-sequences-matters-potential-time-and-money-saver-7e6fa57067b2).

**Comment by Ber666** [comment]
That makes sense. Thank you!
