### ISSUE TITLE
Recommendations to save, store & re-use results?

### ISSUE THREAD

**Issue by smach** [meta-llama/llama-recipes#598]
### 🚀 The feature, motivation and pitch

Thank you for this notebook. It would be helpful to add suggested code for storing and retrieving text embeds with Faiss, and also code for storing and retrieving the summary index somewhere. Storage and retrieval are critical for real-world use, even locally. People don't want to re-index everything every time they have a question.

**Comment by init27** [comment]
@smach Thanks for checking out the tutorial and feedback. We will take a look on improving the [notebook](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/RAG/hello_llama_cloud.ipynb)
