### ISSUE TITLE
pre-training recipe

### ISSUE THREAD

**Issue by enpassanty** [meta-llama/llama-recipes#6]
Any plans to add a recipe for further pre-training on custom data with optional tokenizer vocab extension in the style of [chinese-llama](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/README_EN.md)?  would love to see that.  thanks

**Comment by chauhang** [comment]
Thanks for the suggestions, we welcome contributions from the community. 

Also suggest testing out the training script from chinese-llama on the llama 2 model. Based on the description, it could be done in two steps -- fine-tune the base llama 2 (pre-trained) model on alpaca dataset, and then use the scripts from chinese-llama for custom vocab. If you get a chance to try this out, will be great if you can update with your findings.

**Comment by jmzeng** [comment]
Also very interested in this. If I wish to use the same tokenizer and just continue pretraining with in-domain data, is it sufficient to use the script in llama-recipes for finetuning? (Instead of using prompt/response format, feed in free-text) 

In essence, what is the difference between continue pretraining with in-domain data and finetuning for prompt/response? Thanks.

**Comment by HamidShojanazeri** [comment]
@jmzeng sorry for the late reply, there few things here, a-finetuning a base model to make a assistant model this requires prompt/response dataset, b- continued pretraining, follows similar objective to base model but you would need a large amount of data and we are talking scale of billions of tokens. c-fine-tuning a base or fine-tuned model on specific task which will require high quality data on that specific task it can be in simple format or prompt response format.

**Comment by mreso** [comment]
Closing this as we'll likely not add more datasets and the [use case of continued full-parameter update is already supported and described](https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/multigpu_finetuning.md#with-fsdp--peft). For massive parallel pre-training have a look at [TorchTitan](https://github.com/pytorch/torchtitan).
