### ISSUE TITLE
Your request to access this repo has been rejected by the repo's authors.

### ISSUE THREAD

**Issue by LianhaoXue** [meta-llama/llama-recipes#607]
### 🚀 The feature, motivation and pitch

Hello!
I got the answer "Your request to access this repo has been rejected by the repo's authors" on huggingface,because I write wrong e-mail in the question.
My huggingface username is LianhaoXue
Could you help me to quash my request.
Thanks.

**Comment by wukaixingxp** [comment]
Hi! Please refer to this [statement](https://huggingface.co/meta-llama/Llama-Guard-3-8B/discussions/13) and reply there with any questions if needed!  Thanks!
