### ISSUE TITLE
Quantization - how to do FP8 quantization for the LLama8B and 70B models?

### ISSUE THREAD

**Issue by vgoklani** [meta-llama/llama-recipes#612]
### 🚀 The feature, motivation and pitch

FP8 is pretty main-stream - just ask Jensen - but I have no idea how to do the FP8 quantization using torch.float8_e4m3fn? Could you please provide the script so I can do the conversion and test/compare the outputs using both 8B and 70B.

I also don't trust the other quantization methods and would prefer to see how it's done using torch.

### Alternatives

AWQ and GPTQ - but I would prefer an official example. 

### Additional context

This is meant to be a tutorial repo!

**Comment by wukaixingxp** [comment]
Hi! Here is some reference codes I can find related to [fp8 on llama-stack](https://github.com/meta-llama/llama-stack/tree/main/llama_toolchain/inference/quantization) and the [pytorch library for fp8 support](https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu/experimental/gen_ai). Let me know if you have any questions!
