### ISSUE TITLE
Mismatch in Llama Guard 2 prompt between llama.meta.com and code - `begin_text`

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [meta-llama/llama-recipes#617]
### System Info

This is independent of torch version. 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

The [llama.meta.com / ... / meta-llama-guard-2/](https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-guard-2/) docs includes the `<|begin_of_text|>` text/tokens in it's usage ;

The current [inference/prompt_format_utils.py](https://github.com/meta-llama/llama-recipes/blob/f531d17287bf11d2cc2a5992e9282c77a70b2f51/src/llama_recipes/inference/prompt_format_utils.py#L60) code does not use this for Llama Guard 2.

Should these beginning tokens be or not used for Llama Guard 2?

### Error logs

No error.

### Expected behavior

Documentation matches code utils.

**Comment by BrunoGomesCoelho** [comment]
One more quick question while I am on this - The [prompt format utils](https://github.com/meta-llama/llama-recipes/blob/f531d17287bf11d2cc2a5992e9282c77a70b2f51/src/llama_recipes/inference/prompt_format_utils.py#L179) has multiple extra tab tokens before the beginning of each bullet point on any specific category description for Llama Guard 3, e.g. https://github.com/meta-llama/llama-recipes/blob/f531d17287bf11d2cc2a5992e9282c77a70b2f51/src/llama_recipes/inference/prompt_format_utils.py#L179

This is likely just to align things in the """ string, but they are parsed by the model ; Do you know if these extra tabs were present at fine-tuning time?

**Comment by init27** [comment]
Thanks for raising the issue-I will take a look
