### ISSUE TITLE
is LengthBasedBatchSampler used for make similar length sentence into one batch?

### ISSUE THREAD

**Issue by hjc3613** [meta-llama/llama-recipes#620]
### System Info

any

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I have read the source code about :

![image](https://github.com/user-attachments/assets/a5701efe-ce21-4ed0-8ae7-016df3138a45)

how it insure that the similar length sentence sampled into one batch? using np.argsort? I do not understand how it achive this

### Error logs

np.argsort(self.lengths)

### Expected behavior

I do not know how to write the code

**Comment by mreso** [comment]
Hi @hjc3613,
yes, it uses np.argsort to get the indices of the sampled sorted by their length (i.e. ids will be sample indices but sorted by sequence length). I then returns these indices which are used to pull the actual samples when creating the batch in the data loader.

Feel free to reopen if you have further questions.

**Comment by hjc3613** [comment]
> Hi @hjc3613,
> yes, it uses np.argsort to get the indices of the sampled sorted by their length (i.e. ids will be sample indices but sorted by sequence length). I then returns these indices which are used to pull the actual samples when creating the batch in the data loader.
> 
> Feel free to reopen if you have further questions.

is there any theory behind this idea？I wander why not use random sample？

**Comment by mreso** [comment]
When samples are selected completely random you usually end up with very long and very short sequences in the same batch. When you create a tensor out of the samples you have to extend the short sequences by padding to have the same length as the longest sequence in the batch. This leads to a lot of wasted compute as the model's operations are applied to the padded areas as well. By batching sequences with similar lengths you avoid the majority of the padding and batches are then randomized instead of samples. An alternative is to used the [packing](https://github.com/meta-llama/llama-recipes/blob/55037e4ed7d47e9cb62f8eaf6855cb3385d4137d/src/llama_recipes/configs/training.py#L15) strategy or to use [nested tensors](https://pytorch.org/tutorials/prototype/nestedtensor.html) but we currently don't support nested tensors in recipes.

**Comment by hjc3613** [comment]
> When samples are selected completely random you usually end up with very long and very short sequences in the same batch. When you create a tensor out of the samples you have to extend the short sequences by padding to have the same length as the longest sequence in the batch. This leads to a lot of wasted compute as the model's operations are applied to the padded areas as well. By batching sequences with similar lengths you avoid the majority of the padding and batches are then randomized instead of samples. An alternative is to used the [packing](https://github.com/meta-llama/llama-recipes/blob/55037e4ed7d47e9cb62f8eaf6855cb3385d4137d/src/llama_recipes/configs/training.py#L15) strategy or to use [nested tensors](https://pytorch.org/tutorials/prototype/nestedtensor.html) but we currently don't support nested tensors in recipes.

sory for my confusion, I have debug it, when debug on line:27 in the above picture, I found that each batch in batches is not the same or similar length, eg: 
batches = [[172, 56, 200, 18], [12, 19, 147, 61]......], 
the correspond ids:
ids = [172, 56, 200, 18, 12, 19, 147, 61......]
the number in which stands for the i-th length in total self.lengths, in my opinion, the result batches may like this:[[200, 172, 147, 61], [56, 19, 18, 12], ......]. I have confused many 2 days...

**Comment by mreso** [comment]
I see, here e.g. [172, 56, 200, 18] is not the length of the samples but the index of the sample in the dataset. Meaning we will select sample with the indices 172, 56, 200 and 18 to create a batch. The samples (tokenized sequences) should have similar lengths then. You can find more info on  [argsort here](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) which returns indices not the original data used to sort.

**Comment by hjc3613** [comment]
> I see, here e.g. [172, 56, 200, 18] is not the length of the samples but the index of the sample in the dataset. Meaning we will select sample with the indices 172, 56, 200 and 18 to create a batch. The samples (tokenized sequences) should have similar lengths then. You can find more info on [argsort here](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) which returns indices not the original data used to sort.

thanks! I misunderstand np.argsort, a clever idea!
