### ISSUE TITLE
Will LLama3.1 will open soruce the  pretrain speech encoder?

### ISSUE THREAD

**Issue by Mddct** [meta-llama/llama-recipes#623]
Will LLama3.1 will open soruce the  pretrain speech encoder?

**Comment by mreso** [comment]
Hi, all Llama 3.1 variants a pure text model. Feel free to reopen if this does not answer your question.

**Comment by Mddct** [comment]
plz ref ： https://ai.meta.com/research/publications/the-llama-3-herd-of-models/， which is a multimodal
