### ISSUE TITLE
Is it  possible to run Llama 3.1 without HF libraries ?

### ISSUE THREAD

**Issue by whatdhack** [meta-llama/llama-recipes#625]
### System Info

latest , linux 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Looking through the llama-recipes, saw references to HuggingFace libraries in many places.  In Llama 3.0 , it was possible to run the 8B and 70B without using any HF libraries such as transformers etc.  

For example this - https://github.com/meta-llama/llama3/blob/main/example_text_completion.py  

### Error logs

N/A

### Expected behavior

Retain ability to run  with a minimal just PyTorch stack.

**Comment by wukaixingxp** [comment]
Hi! Here is the [PR](https://github.com/meta-llama/llama-models/pull/108) that provide examples to run Llama 3.1 without HF libraries. Please take a look and let me know if you have more questions!

**Comment by whatdhack** [comment]
The PR  is gone from  llama-models main.
