### ISSUE TITLE
How to save llama3-70b checkpoints if training with FSDP and peft?

### ISSUE THREAD

**Issue by lemon-awa** [meta-llama/llama-recipes#626]
### 🚀 The feature, motivation and pitch

I am currently fine-tuning a Llama3-70B model using LoRA on a system with 4x80G GPUs, employing Fully Sharded Data Parallel (FSDP) for memory efficiency. I intend to save checkpoints during the fine-tuning process. However, directly invoking `model.save_pretrained(train_config.output_dir)` to save checkpoints results in` CUDA out-of-memory` errors. 

### Alternatives

I attempt to move the model to the CPU to save checkpoints, I encounter an error like` AssertionError: Expects tensor to be on the compute device cuda:0, was on cpu`.

**Comment by mreso** [comment]
Hi @lemon-awa so you mean you enabled train_config.run_validation and train_config.save_model in you training config and now its failing at the [end of the epoch ](https://github.com/meta-llama/llama-recipes/blob/9b3dabcaac78980eae40005bbc8b1a8276c82af3/src/llama_recipes/utils/train_utils.py#L238C27-L238C42)? Or did you put save_pretrained somewhere else in the train method?

**Comment by mreso** [comment]
I am able to reproduce with context_length 2048. Default fails before save_pretrained. What context_length are you running this with?

**Comment by mreso** [comment]
Should be fixed with #629, let me know if it does not work for you.

**Comment by lemon-awa** [comment]
Thanks! It works for me!
