### ISSUE TITLE
How to make inference during FSDP and lora fine-tuning process?

### ISSUE THREAD

**Issue by lemon-awa** [meta-llama/llama-recipes#631]
### 🚀 The feature, motivation and pitch

I am currently fine-tuning a **Llama3.1-70B** model using **LoRA** on a system with 4x80G GPUs, employing Fully Sharded Data Parallel (**FSDP**) for memory efficiency. During the fine-tuning process, I want to perform inference(get results of `model.generate()`) to monitor the model’s fine-tuning progress. 

### Alternatives

I tried to set `model.eval()` and use `model.generate()` directly, but it seems that models under FSDP cannot directly use `model.generate`. Then  I tried saving the model’s PEFT checkpoint and then reloading the model. However, this led to errors such as` NCCL Timeout`,` NCCL Watchdog Termination`, and ultimately, the program was aborted due to receiving a `SIGABRT signal`.

**Comment by HamidShojanazeri** [comment]
@lemon-awa generally its not very well supported path in FSDP and its not meant to be used for inference due to its high cost for all_gather during each forward call. Please take a look at this issue. it might be helpful. https://github.com/pytorch/pytorch/issues/123962
