### ISSUE TITLE
Clarification on Evaluation Results for Llama Guard 3

### ISSUE THREAD

**Issue by sheli-kohan** [meta-llama/llama-recipes#633]
### System Info

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2+cu118

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I am currently evaluating the Llama Guard 3 model using the evaluation notebook provided in the llama-recipes repo: [Llama Guard Customization via Prompting and Fine-Tuning](https://github.com/meta-llama/llama-recipes/blob/main/recipes/responsible_ai/llama_guard/llama_guard_customization_via_prompting_and_fine_tuning.ipynb).

When I ran the evaluation on the ToxicChat dataset, I observed an average precision of **30.20%**. This was with the following configurations: split="test".

However, I noticed a discrepancy when comparing this result to the [Llama Guard Model Card](https://github.com/meta-llama/PurpleLlama/blob/main/Llama-Guard/MODEL_CARD.md), which reports an average precision of **62.6%**.  even though the metric is referred to Llama Guard , I believe this degradation means some error in this notebook.

In other matter, we are failing to replicate paper results also for open ai mod eval dataset by category ([figure 2 in the paper](https://scontent.ftlv5-1.fna.fbcdn.net/v/t39.2365-6/408725049_3688557441468029_8103913771964668529_n.pdf?_nc_cat=100&ccb=1-7&_nc_sid=3c67a6&_nc_ohc=J9E3fv4CdawQ7kNvgGCWfkd&_nc_ht=scontent.ftlv5-1.fna&oh=00_AYBECymkNoF_oD98-bKT2VA4ckDSzjJToN8kNgrI4y_eWg&oe=66C3A759)). if you'll be able to share the library or code you used for this evaluation that will be very helpful

Could you please provide any insights or guidance on this difference in performance?

Thank you for your time and assistance.

Best regards,

Sheli Kohan

### Error logs

average precision 30.02%

### Expected behavior

average precision 62.6%

**Comment by init27** [comment]
Thanks for flagging @sheli-kohan!

@albertodepaola Can you help take a look please?

**Comment by sheli-kohan** [comment]
hi,

It seems that the notebook correctly calls build_default_prompt(AgentType.USER, create_conversation(....), **LlamaGuardVersion.LLAMA_GUARD_3.name**). However, in [this](https://github.com/meta-llama/llama-recipes/blame/main/src/llama_recipes/inference/prompt_format_utils.py#L61) script, it appears that the Llama Guard 3 instructions are referencing PROMPT_INSTRUCTIONS_2, which might be one source of the issue. You can check it here: https://github.com/meta-llama/llama-recipes/blame/main/src/llama_recipes/inference/prompt_format_utils.py#L61

i've tried to use PROMPT_INSTRUCTION as in Llama guard 3 model card but reach only AUCPR of 45%

**Comment by init27** [comment]
@sheli-kohan Thank you very much for digging into the source and pointing this out! I will take a look.

> i've tried to use PROMPT_INSTRUCTION as in Llama guard 3 model card but reach only AUCPR of 45%

Do you mean using the correct special tokens still doesn't give right result?

**Comment by sheli-kohan** [comment]
I've updated the **prompt** format to be compatible with **Llama Guard 3**, instead of **Llama Guard 2**.

I believe the other differences stem from the way `parse_logprobs(prompts, type: Type)` calculates the class probabilities. Currently, it uses `prompt["logprobs"][0][1]` for this calculation. However, I would expect the calculation to focus on the token 'safe', or if the token is unsafe, on the violative class number that appears after the token 'S'.

The current use of `prompt["logprobs"][0][1]` would only partially apply if I were still using **Llama Guard 2**.

I would appreciate your input on this.
thanks,
Sheli

**Comment by MLRadfys** [comment]
Hi,

I encountered the same problem! Tried to reproduce the Llama Guard 3 evaluation results using the provided examples and got an AP of 24%. 
For me it looks like the model output is wrong, when compared to the GT labels.

Any help on this would be highly appreciated.

Thanks in advance,

M

**Comment by sheli-kohan** [comment]
@init27 when I used the "safe" and "unsafe" token probabilities + fixed the prompt to llama guard 3, I reached AUCPR of 50. still lower than presented 62 for llama guard 2. 
I even tried worked with Llama guard 2 and this yield even lower AUCPR

**Comment by tryrobbo** [comment]
Thanks for raising this issue @sheli-kohan . Indeed it does seem to be an issue with the notebook. We will endeavor to work out what's going on here, and hope to update the notebook in due course.
Can I ask that you open a PR with the modifications you have made which have made an improvement so far. I'll discuss with colleagues how we can work out the issue here. 
Thanks again for looking at this. 
@tryrobbo (author of the LlamaGuard notebook)

**Comment by sheli-kohan** [comment]
Hi @tryrobbo , thanks for your assistance. 
It seems I don't have permission to submit a PR in this repo. Could you please grant me access?

this is [my notebook](https://colab.research.google.com/drive/1Gf0gsZkVSEUrObr-VKBdteG98fbaZy1D?usp=sharing) with some bug fixes and additional category-wise evaluation trial (zero shot only). 

Desired output is

- At least 62 AUPRC on binary classification
- Category-wise evaluation that reach the zero-shot ones presented in Fig. 2 in [Llama guard 3 paper](https://arxiv.org/pdf/2312.06674)

![Screenshot 2024-08-29 at 12 44 43](https://github.com/user-attachments/assets/753889fd-719b-4133-b0fb-1e7fb8a643fe)

**Comment by mlaugharn** [comment]
Hi, any update on this?
