### ISSUE TITLE
file : inference.py   RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by nkfnn** [meta-llama/llama-recipes#64]
<img width="1226" alt="9cf233cb83e8ec72aa245dcbd8774a5" src="https://github.com/facebookresearch/llama-recipes/assets/44599938/91d2c39a-3deb-42be-babf-1200f3ac548f">

**Comment by nkfnn** [comment]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by kk990926** [comment]
> RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Is your server multi-card or single-card, I've called different cards when loading data before and got similar errors, maybe you can try to add CUDA_VISIBLE_DEVICES=0 before execution.

**Comment by nkfnn** [comment]
> > 运行时错误：CUDA 错误：设备端断言触发的 CUDA 内核错误可能会在其他某个 API 调用中异步报告，因此下面的堆栈跟踪可能不正确。对于调试，请考虑传递 CUDA_LAUNCH_BLOCKING=1。编译 以启用设备端断言。`TORCH_USE_CUDA_DSA`
> 
> 你的服务器是多卡还是单卡，我之前在加载数据时调用过不同的卡，并得到了类似的错误，也许你可以在执行前尝试添加 CUDA_VISIBLE_DEVICES=0。

I encountered this issue when using two GPUs. My single GPU graphics memory is not sufficient and I can only use two GPUs

**Comment by HamidShojanazeri** [comment]
@nkfnn can you pls provide more details what are you trying to achieve with your setting/command your running?

**Comment by Longice** [comment]
> > > 运行时错误：CUDA 错误：设备端断言触发的 CUDA 内核错误可能会在其他某个 API 调用中异步报告，因此下面的堆栈跟踪可能不正确。对于调试，请考虑传递 CUDA_LAUNCH_BLOCKING=1。编译 以启用设备端断言。`TORCH_USE_CUDA_DSA`
> > 
> > 
> > 你的服务器是多卡还是单卡，我之前在加载数据时调用过不同的卡，并得到了类似的错误，也许你可以在执行前尝试添加 CUDA_VISIBLE_DEVICES=0。
> 
> I encountered this issue when using two GPUs. My single GPU graphics memory is not sufficient and I can only use two GPUs

Did you solved this problem, i meet the same error when run 70B-chat model for inference.

**Comment by HamidShojanazeri** [comment]
@Longice sorry I am not able to repro it. Please make sure you are using the latest code.

```
 python inference.py --model_name PATH/to/70B  --prompt_file samsum_prompt.txt
 ```

**Comment by Longice** [comment]
I am using the latest code, but i am using chat_completion.py. Here is my commond, and there is 4 GPU loading models:
`python inference/chat_completion.py --model_name /data/huggingface-models/llama/llama-2-70b-chat --prompt_file inference/chats.json`

**Comment by roy-sc** [comment]
I have had the same error for running inference with just 2 GPUs. I could resolve the issue on my side by downgrading the version of `accelerate` from 0.22.0 to 0.21.0.
For anyone having the same issue as me.

**Comment by mengmeng233** [comment]
Did you solved this problem?  I meet the same error.

**Comment by Alex-debug41** [comment]
set cuda_visible_devices to 0 can sovle this, just use one gpu

**Comment by JinaoLiu** [comment]
I had the same problem. It works with a single card, but multiple cards will report an error
