### ISSUE TITLE
New metrics for benchmark 

### ISSUE THREAD

**Issue by mathmax12** [meta-llama/llama-recipes#652]
### 🚀 The feature, motivation and pitch

Very nice work, Llama team. Llama is the most popular open-source LLM project and has been adopted for different platforms. It will be great to see more metrics, e.g., tokens/s, sample/s, and % TFLOps, collected during training for benchmarking purposes.

**Comment by init27** [comment]
Thanks for the feedback!
Could you please share what metrics you'd love to see (if any) apart from the ones shared in our evals?

**Comment by SeanSong-amd** [comment]
Here are some thoughts that come to mind:
Average TFLOP/s per GPU
Average Tokens/s per GPU
Average Samples/s
GPU Utilization (% TFLOP/s per GPU)

**Comment by mathmax12** [comment]
Here are some thoughts that come to mind:
Average TFLOP/s per GPU
Average Tokens/s per GPU
Average Samples/s
GPU Utilization (% TFLOP/s per GPU)
