### ISSUE TITLE
  FP8 support for training 

### ISSUE THREAD

**Issue by mathmax12** [meta-llama/llama-recipes#655]
### 🚀 The feature, motivation and pitch

Is there a plan to add FP8 support for training?

**Comment by wukaixingxp** [comment]
Hi! We rely on the FP8 feature from Pytorch, which I think the FP8 training is still experimental. Please check [this repo](https://github.com/pytorch/ao/tree/main/torchao/float8) and [this blog](https://pytorch.org/blog/accelerating-llama3/) for more details.
