### ISSUE TITLE
finetuning.py is failing with error "ValueError: too many values to unpack (expected 2)"

### ISSUE THREAD

**Issue by Utsavv** [meta-llama/llama-recipes#661]
### System Info

Collecting environment information...
PyTorch version: 2.4.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro T2000
Nvidia driver version: 555.99
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2400
DeviceID=CPU0
Family=207
L2CacheSize=2048
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2400
Name=Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.1
[pip3] onnx==1.16.2
[pip3] onnxruntime==1.19.0
[pip3] torch==2.4.0+cu118
[pip3] torchaudio==2.4.0+cu118
[pip3] torchvision==0.19.0+cu118
[conda] Could not collect

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

python finetuning.py  --use_peft --peft_method lora --quantization 8bit --model_name C:\Users\vermau\.cache\lm-studio\models\lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\ --C:\Users\vermau\.cache\lm-studio\models\lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\OutputModel

Gave following error -

### Error logs

```DeprecationWarning: `torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead  
  from torch.distributed._shard.checkpoint import (
Traceback (most recent call last):
  File "C:\W\GIT\Downloads\llama-recipes\recipes\quickstart\finetuning\finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ontext, name)
ontext, name)
ontext, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ontext, name)
ontext, name)
ontext, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_recipes\finetuning.py", line 76, in main

    update_config((train_config, fsdp_config), **kwargs)        
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_recipesgs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_recipes\finetuning.py", line 76, in main
    update_config((train_config, fsdp_config), **kwargs)
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_recipes\utils\config_utils.py", line 25, in update_config
    update_config(c, **kwargs)
  File "C:\Users\vermau\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_recipes\utils\config_utils.py", line 32, in update_config
    config_name, param_name = k.split(".")
    ^^^^^^^^^^^^^^^^^^^^^^^
**ValueError: too many values to unpack (expected 2)**```

### Expected behavior

fine tuning example should work

**Comment by mreso** [comment]
Hi @Utsavv 
thanks for reporting this!

It seems like the `output_dir` argument is missing in your command.

Instead of 
```
python finetuning.py --use_peft --peft_method lora --quantization 8bit --model_name C:\Users\vermau.cache\lm-studio\models\lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\ --C:\Users\vermau.cache\lm-studio\models\lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\OutputModel
```
It should be:
```
python finetuning.py --use_peft --peft_method lora --quantization 8bit --model_name C:\Users\vermau.cache\lm-studio\models\lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\ --output_dir C:\Users\vermau.cache\lm-studio\models\lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\OutputModel
```

**Comment by mreso** [comment]
Closing this as I think its resolved. Please let me know if this its not the case.
