### ISSUE TITLE
Error in custom_dataset recipe

### ISSUE THREAD

**Issue by lucas-ventura** [meta-llama/llama-recipes#669]
### System Info

2.4.0+cu121

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

In the `tokenize_dialog(dialog, tokenizer)` function, lines 15 and [16](https://github.com/meta-llama/llama-recipes/blob/3e39ed05bdd6426bd0c41253d1b18e478e2cb670/recipes/quickstart/finetuning/datasets/custom_dataset.py#L15) are currently:

```python
dialog_tokens = tokenizer.apply_chat_template(dialog)
dialog_tokens = dialog_tokens[:-4]  # Remove generation prompt <|start_header_id|>assistant<|end_header_id|>\n\n
```

However, the string `"<|start_header_id|>assistant<|end_header_id|>\n\n"` is only appended if `tokenizer.apply_chat_template(dialog, add_generation_prompt=True)` is called with `add_generation_prompt=True`. Since `add_generation_prompt` is `False` by default, this string isn't added. 

As a result, line 16 should be removed.

Thank you for the cool work!

### Error logs

There are no error logs. The response is simply being cut off.

### Expected behavior

The string ``<|start_header_id|>assistant<|end_header_id|>\n\n`` is only added when ``add_generation_prompt=True`` in ``tokenizer.apply_chat_template(dialog, add_generation_prompt=True)``. 
Therefore, it should either be explicitly added with ``add_generation_prompt=True`` and then removed with ``[:-4]``, or it should not be added at all. This would ensure that the response isn't truncated.

**Comment by mreso** [comment]
Thanks @lucas-ventura for reporting this, there has been a change in the default behavior of the tokenizer due to a config update. This will be mitigated shortly by https://github.com/meta-llama/llama-recipes/pull/665

**Comment by mreso** [comment]
Closing after #665 got merged. Feel free to reopen if the problem persists.
