### ISSUE TITLE
``data_path`` not accessible in ``get_custom_dataset`` when using ``finetuning.py``

### ISSUE THREAD

**Issue by lucas-ventura** [meta-llama/llama-recipes#670]
### System Info

2.4.0+cu121

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

**Description:**
I'm experiencing an issue when attempting to fine-tune using `finetuning.py` with a custom dataset. The `data_path` specified in the dataset's dataclass doesn't seem to be accessible in the `get_custom_dataset` function.

#### Description
When calling `finetuning.py` with the `--dataset "custom_dataset"` flag, along with `--custom_dataset.file` and `--custom_dataset.data_path`, the `data_path` does not seem to be available within the `get_custom_dataset` function.

#### Steps to Reproduce
1. Run the `finetuning.py` script with the following flags:
    ```
    --dataset "custom_dataset" 
    --custom_dataset.file "custom_dataset.py" 
    --custom_dataset.data_path "path/to/csv"
    ```
2. In the custom dataset file (`custom_dataset.py`), include the following function to print the `data_path`:
    ```python
    def get_custom_dataset(dataset_config, tokenizer, split):
        print(f"dataset_config.data_path: {dataset_config.data_path}")
    ```
3. Launch the script.

#### Reference
The `data_path` attribute is defined in the `custom_dataset` class in [datasets.py](https://github.com/meta-llama/llama-recipes/blob/3e39ed05bdd6426bd0c41253d1b18e478e2cb670/src/llama_recipes/configs/datasets.py#L35)

Please let me know if any additional information is needed to debug this issue. Thank you!

### Error logs

```
Warning: custom_dataset does not accept parameter: custom_dataset.data_path  
```

#### Expected Behavior
The `data_path` specified in the command line (`--custom_dataset.data_path "path/to/csv"`) should be accessible within the `get_custom_dataset` function and printed out correctly.

#### Actual Behavior
The `data_path` is not available in the `get_custom_dataset` function when it is printed, indicating that the value is not being passed correctly.

**Comment by mreso** [comment]
Hi @lucas-ventura 
I tried to repro the issue and was able to repro on v0.0.3. Is that the version you're running as well?
If thats the case please update to the newest main by running
```bash
pip install -U git+https://github.com/meta-llama/llama-recipes
```
That should solve the issue.

**Comment by lucas-ventura** [comment]
I've updated to v0.0.3:
```
$ pip show llama_recipes
Name: llama-recipes
Version: 0.0.3
Summary: ...
```

And I still have the same error:
```
 AttributeError: 'custom_dataset' object has no attribute 'data_path'
```

**Comment by mreso** [comment]
In 0.0.3 I was able to reproduce your issue. But 0.0.3 is already a couple of month old. Please update to the current tip of main with the command from my previous comment. The issue is fixed in the current main branch.

**Comment by lucas-ventura** [comment]
@mreso you're right, once I updated to the latest version, I was able to use ``custom_dataset.data_path`` without any issues! Thank you!
