### ISSUE TITLE
using custom dataset with llama3 - 8b instuct

### ISSUE THREAD

**Issue by aysenuratlac** [meta-llama/llama-recipes#673]
### System Info

Google Collab

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### 🐛 Describe the bug

I want to run recipes/quickstart/finetuning/quickstart_peft_finetuning.ipynb with my own dataset but when I look at recipes/quickstart/finetuning/datasets/custom_dataset.py I realized this is the format for llama 2 (special tokens etc). So I want to learn how can I modify this in order to use my own data with llama 3 instruct model.  I tried to use old version but got an error. Here is my code : 
B_INST = "[INST]"
E_INST = "[/INST]"
# Custom Dataset class
class CustomDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=512):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        # Each item is a dictionary with 'instruction' and 'answer'
        item = self.data[idx]
        instruction = item["Instruction"]
        answer = item["Answer"]

        # Tokenize the instruction and answer
        instruction_tokens = self.tokenizer.encode(f"{B_INST} {instruction.strip()} {E_INST}", add_special_tokens=False)
        answer_tokens = self.tokenizer.encode(f"{answer.strip()} {self.tokenizer.eos_token}", add_special_tokens=False)

        # Concatenate instruction and answer tokens
        input_ids = list(itertools.chain(instruction_tokens, answer_tokens))

        # Create labels: the instruction tokens will be -100 to ignore in loss calculation
        labels = [-100] * len(instruction_tokens) + answer_tokens

        return {
            "input_ids": torch.tensor(input_ids),
            "attention_mask": torch.tensor([1] * len(input_ids)),
            "labels": torch.tensor(labels)
        }

# Function to load the dataset
def load_custom_dataset(file_path, tokenizer):
    with open(file_path, 'r') as f:
        data = json.load(f)
    return CustomDataset(data, tokenizer)

# Example of loading training and validation datasets
train_data_path = "/content/drive/MyDrive/train_data.json"
validation_data_path = "/content/drive/MyDrive/test_data.json"

train_dataset = load_custom_dataset(train_data_path, tokenizer)
val_dataset = load_custom_dataset(validation_data_path, tokenizer)

# Create DataLoaders
train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=8, shuffle=True)
val_dataloader = torch.utils.data.DataLoader(val_dataset, batch_size=8) . While run the training part I got an error.

To sum up, I would be glad if you can upload an example which compatible with llama 3 instruct model.

### Error logs

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-14-361c3520b47c>](https://localhost:8080/#) in <cell line: 15>()
     13 
     14 # Start the training process
---> 15 results = train(
     16     model,
     17     train_dataloader,

8 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/collate.py](https://localhost:8080/#) in collate_tensor_fn(batch, collate_fn_map)
    212         storage = elem._typed_storage()._new_shared(numel, device=elem.device)
    213         out = elem.new(storage).resize_(len(batch), *list(elem.size()))
--> 214     return torch.stack(batch, 0, out=out)
    215 
    216 

RuntimeError: stack expects each tensor to be equal size, but got [26] at entry 0 and [36] at entry 1

### Expected behavior

I also tried to use different method. Defined a new function:
def get_formatted_dialogs(dialogs):
    formatted_dialogs=''.join([
        f'<|start_header_id|>{entry["role"]}<|end_header_id|>{entry["content"]}<|eot_id|>' for dialog in dialogs for entry in dialog
    ])
    formatted_dialogs = "<|begin_of_text|>"+formatted_dialogs+"<|start_header_id|>assistant<|end_header_id|>"
    return formatted_dialogs
def get_llama_response(dialogs: list, model, tokenizer, p_max_new_token:float, p_temperature: float, top_p: float) -> str:
    formatted_dialogs = get_formatted_dialogs(dialogs)  # Dialogları belirli bir formatta düzenler
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token  # Tokenizer'ın pad token'ı yoksa, pad token'ı eos token olarak ayarlar

    # Dialogları tokenlara dönüştürüp modelin girdi formatına hazırlar
    inputs = tokenizer(formatted_dialogs, return_tensors="pt", truncation=True, padding=True)
    inputs = {key: val.to(model.device) for key, val in inputs.items()}  # Tüm girdileri modelin cihazına taşır
    print("inputs hazırlandı, output generate ediliyor...")

    # Modelin çıktısını oluşturur (generate) ve çıktıyı (response) alır
    output = model.generate(**inputs, max_new_tokens=p_max_new_token, temperature=p_temperature, top_p=top_p)

    # Modelin ürettiği çıktıyı (tokenları) metne çevirir
    response_text = tokenizer.decode(output[0], skip_special_tokens=True).strip()

    # Asistanın son cevabını almak için "assistant" kelimesinden sonrasını alır
    if "assistant" in response_text:
        last_response = response_text.split("assistant")[-1].strip()
    else:
        last_response = response_text.strip()

    return last_response

But i couldnt get a logical answers.

**Comment by mreso** [comment]
Hi @aysenuratlac what version of llama-recipes do you have installed? From your pasted code it must be pre v0.0.3. To train with the llama 3 template I suggest updating your llama-recipes version to at leas v0.0.3 or current main branch, and use this [custom_dataset.py](https://raw.githubusercontent.com/meta-llama/llama-recipes/d9939cd0cf34155baea14d0402de9ac6bd5071af/recipes/quickstart/finetuning/datasets/custom_dataset.py) from PR #665 which fixes some issues in the old script and adjusts it to the updated default values of the llama3  tokenizer.

**Comment by mreso** [comment]
Closing this as #665 got merged. It should work with llama 2, 3, 3.1. Feel free to reopen if this is not the case for you.
