### ISSUE TITLE
``pip install -e .`` or ``pip install -U git+https://github.com/meta-llama/llama-recipes`` leads to ResolutionTooDeep error

### ISSUE THREAD

**Issue by lucas-ventura** [meta-llama/llama-recipes#674]
### System Info

python3.12
2.4.1+cu121

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

When running `pip install llama-recipes`, everything installs correctly without issues. However, when I attempt to run either:

- `pip install -e .`
- `pip install -U git+https://github.com/meta-llama/llama-recipes`

The installation process takes a long time and eventually results in the following error:

```bash
File "path/to/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

### Steps taken:
- I have tried both **conda** and **virtual environments**.
- Tested across different Python versions: 3.9, 3.10, 3.11, and 3.12.
- I also tried on a different computer and encountered the same issue.

### Additional attempt:
- I tried using the following workaround:

  ```bash
  pip install git+https://github.com/notatallshaw/pip.git@prefer-conflicting-causes
  ```

  This solved the issue during installation. However, after installing, I encountered another problem when trying to save the model:

  ```bash
  [rank1]: AttributeError: 'Params4bit' object has no attribute 'absmax'
  ```

Any guidance on resolving this issue would be appreciated. Thank you!

### Error logs

```bash
File "path/to/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

### Expected behavior

The installation should complete successfully, similar to the ``pip install llama-recipes`` command.

**Comment by aishwaryap** [comment]
Running into the same installation issue with both conda and venv with Python 3.9.18
```
ERROR: Exception:
Traceback (most recent call last):
  File "/cm/local/apps/python39/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/cm/local/apps/python39/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/cm/local/apps/python39/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/cm/local/apps/python39/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/cm/local/apps/python39/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/cm/local/apps/python39/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
```

**Comment by mreso** [comment]
Hi @lucas-ventura @aishwaryap I hope your installation troubles are solved after #676. Regarding the absmax, I have isolated the issue to [this line](https://github.com/meta-llama/llama-recipes/blob/98707b72fda091b2b20e3ab2ffaf9a86e4fccd84/src/llama_recipes/model_checkpointing/checkpoint_handler.py#L273) where we configure cpu_offload=True. Not sure yet why but disabling this lets it run successful for me. Hope to have a real fix soon.

**Comment by lucas-ventura** [comment]
Yes! Everything works now, thank you!!

**Comment by PanagiotisFytas** [comment]
Is there any update on [rank1]: AttributeError: 'Params4bit' object has no attribute 'absmax' without disabling the cpu_offload flag?

**Comment by lucas-ventura** [comment]
It is working for me. How are you installing llama-recipes?

**Comment by PanagiotisFytas** [comment]
With:
```
git clone git@github.com:meta-llama/llama-recipes.git
cd llama-recipes
pip install -U pip setuptools
pip install -e .
```
