### ISSUE TITLE
Need guide on how can I use fine-tuned model for inferencing.

### ISSUE THREAD

**Issue by himanshushukla12** [meta-llama/llama-recipes#682]
### 🚀 The feature, motivation and pitch

Hello I tried to do inferencing but facing some issues, also there is no `readme.md` in `src/llama_recipes/inference` directory, please someone add to this so that it will be easy to use fine-tuned model load and doing inferencing.

**Comment by albertodepaola** [comment]
Hi @himanshushukla12! The inference instructions are located in the quickstart section of the repo, please check them out as they also list how to do inference with fine tuned models: https://github.com/meta-llama/llama-recipes/tree/main/recipes/quickstart/inference/local_inference
