### ISSUE TITLE
when use "--from_peft_checkpoint", I get a typerror

### ISSUE THREAD

**Issue by 24kMengXin** [meta-llama/llama-recipes#709]
### System Info

PyTorch  2.1.2
Python  3.10(ubuntu22.04)
Cuda  11.8
GPU
A800-80GB(80GB) * 1
CPU
14 vCPU Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### 🐛 Describe the bug

I used the Llama-3-8b-instruct to lora fine-tune, by running `/recipes/quickstart/finetuning/finetuning.py`.

All scripts are official except those related to dataset construction and `src/llama_recipes/utils/train_utils.py`. I modify the `train_utils.py` following #691  (which is before the official merging) several days ago to skip the validation. The lora fine-tune process is ok, the model can be saved and work. 

When I load the peft checkpoint to continue the fine-tune with more epochs, I got a type error as **Error logs** shown.

However, when I delete the `()` of `peft_config = model.peft_config()` in `src/llama_recipes/finetuning.py`, the script works and succeed to save `adapter_model.safetensors` and `adapter_config.json`.

I would like to know if my modification in `src/llama_recipes/finetuning.py` is suitable?

### Error logs

```
Traceback (most recent call last):
  File "/root/ner_in_assis_large_data/recipes/quickstart/finetuning/finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/ner_in_assis_large_data/src/llama_recipes/finetuning.py", line 150, in main
    peft_config = model.peft_config()
TypeError: 'dict' object is not callable
```

### Expected behavior

Expect that the script `/recipes/quickstart/finetuning/finetuning.py` works with the arg `--from_peft_checkpoint`.

**Comment by mreso** [comment]
Hi @24kMengXin yes, that is an error here as model.peft_config returns a dict or a PeftConfig which is a dataclass. Both are not callable. Would you be interested in providing a PR for this?

**Comment by wukaixingxp** [comment]
@24kMengXin Do you want to run a test on latest main? Let me know if the main branch also has this error. Thanks!

**Comment by 24kMengXin** [comment]
> Hi @24kMengXin yes, that is an error here as model.peft_config returns a dict or a PeftConfig which is a dataclass. Both are not callable. Would you be interested in providing a PR for this?

> @24kMengXin Do you want to run a test on latest main? Let me know if the main branch also has this error. Thanks!

I got a same error when I run the script with the latest main.
Here's the Error Logs:
```
/root/llama-recipes/src/llama_recipes/model_checkpointing/checkpoint_handler.py:17: DeprecationWarning: 
`torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead
  from torch.distributed._shard.checkpoint import (
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  9.58it/s]
--> Model /root/autodl-tmp/model/llama-3-8b-instruct
--> /root/autodl-tmp/model/llama-3-8b-instruct has 8030.261248 Million params
Traceback (most recent call last):
  File "/root/llama-recipes/recipes/quickstart/finetuning/finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/llama-recipes/src/llama_recipes/finetuning.py", line 170, in main
    peft_config = model.peft_config()
TypeError: 'dict' object is not callable
```
Here's the configs I set them differently from the default:
```
from dataclasses import dataclass
@dataclass
class train_config:
    model_name: str="/root/autodl-tmp/model/llama-3-8b-instruct"
    run_validation: bool=False
    dataset = "custom_dataset"
    use_peft: bool=True # use parameter efficient fine tuning
    from_peft_checkpoint: str="/root/lora-llama3-ft/save/PEFT/model_ner_in_assis" # if not empty and use_peft=True, will load the peft checkpoint and resume the fine-tuning on that checkpoint
    output_dir: str = "/root/lora-llama3-ft/save/PEFT/model_test"
    save_metrics: bool = True # saves training metrics to a json file for later plotting
    flop_counter_start: int = 20 # The step to start profiling, default is 3, which means after 3 steps of warmup stage, the profiler will start to count flops.
```
And when I delete th` () `of `peft_config = model.peft_config()` in `/src/llama_recipes/finetuning.py`, the script works.

```
/root/llama-recipes/src/llama_recipes/model_checkpointing/checkpoint_handler.py:17: DeprecationWarning: `torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead
  from torch.distributed._shard.checkpoint import (
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  9.09it/s]
--> Model /root/autodl-tmp/model/llama-3-8b-instruct

--> /root/autodl-tmp/model/llama-3-8b-instruct has 8030.261248 Million params

trainable params: 54,525,952 || all params: 8,084,787,200 || trainable%: 0.6744
```
I also test that if finetune a model without load from a peft checkpoint, this error won't be occured with the latest main. Whether I modify the `/src/llama_recipes/finetuning.py`, it won't be occured.

I've provided a PR in #717 .

**Comment by wukaixingxp** [comment]
Thanks for your PR. I think your PR should work, but the [model.peft_config()](https://github.com/huggingface/peft/blob/v0.13.0/src/peft/peft_model.py#L189) has been defined and it was working before. Just curious what is your peft library version.

**Comment by 24kMengXin** [comment]
> @24kMengXin Thanks for your PR. I think your PR should work, but the [model.peft_config()](https://github.com/huggingface/peft/blob/v0.13.0/src/peft/peft_model.py#L189) has been defined and it was working before. Just curious what is your peft library version.

The version is `0.12.0`. 
Here's the huggingface peft source.
https://github.com/huggingface/peft/blob/v0.12.0/src/peft/peft_model.py
It seems that peft_config is a attribute (dict) instead of a method, so use `()` to ask the value will get the error.
Cause I'm not good at coding, if I understand anything wrong, please correct me.
