### ISSUE TITLE
Adding Crusoe examples to 3p_integrations

### ISSUE THREAD

**Issue by ethxnp** [meta-llama/llama-recipes#713]
### 🚀 The feature, motivation and pitch

Prospective [Crusoe](https://crusoe.ai/) customers would like to understand how to perform common Llama workflows (inference, fine-tuning, training) on our cloud. We'd like to contribute solutions centered around Llama to the 3p_integrations repo, beginning with a tutorial on benchmarking FP8 quants served via vLLM. The tutorial covers how to deploy resources on Crusoe, start a vLLM server, run and interpret benchmarks, and finally how to create fp8 quants of existing Llama3 finetunes.

We hope for this to be the first of a series of solutions for common Llama workflows!

**Comment by init27** [comment]
Hi @ethxnp thanks for starting the chat! 

Yes-this would be really cool to have-please feel free to start a PR and tag me if you have any Qs!

**Comment by ethxnp** [comment]
@init27 thank you! Just submitted a [PR](https://github.com/meta-llama/llama-recipes/pull/716)

**Comment by HamidShojanazeri** [comment]
Thansk @ethxnp for the PR
