### ISSUE TITLE
Feature Request 「plz support InternLM2.5」

### ISSUE THREAD

**Issue by boshallen** [meta-llama/llama-recipes#721]
### 🚀 The feature, motivation and pitch

Hi,

I noticed that the repository currently lacks support for the InternLM2.5-7B (1.8B, 20B) model, which may cause compatibility issues or missing steps for users trying to implement it. It would be beneficial to update the repository with detailed instructions or tools for integrating and using the InternLM2.5-7B model, ensuring the content remains relevant.

I believe that adding this support would significantly enhance the usability of the project. While some manual adjustments are possible, official guidance or toolchain support would be much more efficient and advantageous, especially for new users.

If possible, including example scripts or demonstrating integration with InternLM2.5-7B would also be a valuable addition.

For further support, please add the InternLM Assistant (WeChat search: InternLM) or join the InternLM Discord(https://discord.com/invite/xa29JuW87d).

**Comment by mreso** [comment]
Hi @boshallen thanks for your proposal. The purpose of this repo is to serve as a resource for users interested in working with Llama models. We're currently not planning on expanding the scope of the repo. If you're interested in contributing fine-tuning recipes for InternLM you might want to consider looking into [TorchTune](https://github.com/pytorch/torchtune) which has a more model-agnostic scope.
