### ISSUE TITLE
Issue with quickstart_peft_finetuning.ipynb

### ISSUE THREAD

**Issue by jihao2021** [meta-llama/llama-recipes#730]
### System Info

First of all, when I tried to use pip install llama-recipes, I ran into issues half way of installation 
Then I switched to using: pip install llama-recipes==0.0.3, it worked. 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

However, while I ran quickstart_peft_finetuning.ipynb, another error popped out at Step 3: 
from llama_recipes.configs.datasets import samsum_dataset
from llama_recipes.utils.dataset_utils import get_dataloader

samsum_dataset.trust_remote_code = True

train_dataloader = get_dataloader(tokenizer, samsum_dataset, train_config)
eval_dataloader = get_dataloader(tokenizer, samsum_dataset, train_config, "val")

After running this cell, the error message looks like this: 
ImportError                               Traceback (most recent call last)
Cell In[5], line 2
      1 from llama_recipes.configs.datasets import samsum_dataset
----> 2 from llama_recipes.utils.dataset_utils import get_dataloader
      4 samsum_dataset.trust_remote_code = True
      6 train_dataloader = get_dataloader(tokenizer, samsum_dataset, train_config)

ImportError: cannot import name 'get_dataloader' from 'llama_recipes.utils.dataset_utils' ([/home1/haoji/.conda/envs/llama-fine-tune-6/lib/python3.12/site-packages/llama_recipes/utils/dataset_utils.py](https://ondemand.carc.usc.edu/home1/haoji/.conda/envs/llama-fine-tune-6/lib/python3.12/site-packages/llama_recipes/utils/dataset_utils.py))

### Error logs

ImportError                               Traceback (most recent call last)
Cell In[5], line 2
      1 from llama_recipes.configs.datasets import samsum_dataset
----> 2 from llama_recipes.utils.dataset_utils import get_dataloader
      4 samsum_dataset.trust_remote_code = True
      6 train_dataloader = get_dataloader(tokenizer, samsum_dataset, train_config)

ImportError: cannot import name 'get_dataloader' from 'llama_recipes.utils.dataset_utils' ([/home1/haoji/.conda/envs/llama-fine-tune-6/lib/python3.12/site-packages/llama_recipes/utils/dataset_utils.py](https://ondemand.carc.usc.edu/home1/haoji/.conda/envs/llama-fine-tune-6/lib/python3.12/site-packages/llama_recipes/utils/dataset_utils.py))

### Expected behavior

Expected the package to be running

**Comment by wukaixingxp** [comment]
@jihao2021 you need to install the latest package by `pip install llama-recipes`, may I know what is the error you see during the pip install?

**Comment by jihao2021** [comment]
@wukaixingxp Here is the output error message after running: pip install llama-recipes
```
Collecting onnx==1.14.1 (from unstructured-inference==0.7.3->unstructured[pdf]->llama-recipes)
  Using cached onnx-1.14.1.tar.gz (11.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      <string>:33: DeprecationWarning: Use shutil.which instead of find_executable
      <string>:34: DeprecationWarning: Use shutil.which instead of find_executable
      Traceback (most recent call last):
        File "/home1/haoji/.conda/envs/llama-fine-tune-9/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home1/haoji/.conda/envs/llama-fine-tune-9/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home1/haoji/.conda/envs/llama-fine-tune-9/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/SLURM_26361956/pip-build-env-_y0122dt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/SLURM_26361956/pip-build-env-_y0122dt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/SLURM_26361956/pip-build-env-_y0122dt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/SLURM_26361956/pip-build-env-_y0122dt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 85, in <module>
      AssertionError: Could not find cmake executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by wukaixingxp** [comment]
The error is from `unstructured[pdf]`,can you try to use conda and `conda install cmake` as discussed [here](https://github.com/ifzhang/ByteTrack/issues/347#issuecomment-1744269195). Alternatively, you can comment out this [line](https://github.com/meta-llama/llama-recipes/blob/main/requirements.txt#L25) and [install from source](https://github.com/meta-llama/llama-recipes?tab=readme-ov-file#install-from-source).

**Comment by jihao2021** [comment]
Thank you, it worked!

**Comment by init27** [comment]
Closing as its resolved!
