### ISSUE TITLE
Add eval code for LLaMA 3.2 text model

### ISSUE THREAD

**Issue by LeoXinhaoLee** [meta-llama/llama-recipes#732]
### 🚀 The feature, motivation and pitch

The current llama-recipes codebase only supports eval for llama 3.1 models. 

It would be very helpful to add eval for llama 3.2 1B-Base/Instruct model as well (especially mmlu and mmlu_pro).

I'm wondering if there's any plan for that to come soon? @wukaixingxp

**Comment by aidando73** [comment]
Hi @wukaixingxp, I've submitted a PR to add support for the llama 3.2 meta evals for the pre-train models (1B and 3B).

Could you PTAL? https://github.com/meta-llama/llama-recipes/pull/801 👈 

Hoping to add more evals and include instruct evals as well, if that SGTY

**Comment by aidando73** [comment]
Hi @LeoXinhaoLee that PR should be merged now.

For 3.2 1B/3B base models I've added mmlu, for 3.2 1B/3B instruct models I've added mmlu, math and gpqa

Could you give that a go when you have the chance? Lmk what your thoughts are

**Comment by LeoXinhaoLee** [comment]
Thank you so much! Will be excited to try out down the road. Thank you again for your help!
