### ISSUE TITLE
Providing a service to customers in Japan using Llama 3.1

### ISSUE THREAD

**Issue by leosaito-valorant** [meta-llama/llama-recipes#783]
### 🚀 The feature, motivation and pitch

Hello. I am planning to provide a service to customers in Japan using Llama 3.1. I would like to know if there are any licensing fees or patent royalties associated with using Llama 3.1.

**Comment by Daniel15** [comment]
My understanding is that you don't need a special license unless your service will have over 700 million users. The license terms for Llama 3.1 are here: https://www.llama.com/llama3_1/license/ and I'd suggest reading over the entire license (and have your lawyer read it, if you have one).

**Comment by HamidShojanazeri** [comment]
@leosaito-valorant Llama is fully open source and as Daniel mentioned you can find the license [here](https://www.llama.com/llama3_1/license/).
