### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by Amerehei** [meta-llama/llama-recipes#784]
I want to use a custom data set, I created my own `custom_dataset.py`, How can I define `tokenizer.chat_template`? 

```
ValueError: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating
```

**Comment by wukaixingxp** [comment]
What model are you using? Can you show me your command?

**Comment by Amerehei** [comment]
@wukaixingxp I'm using

```
torchrun --nnodes 1 \
   --nproc_per_node 8  \
   finetuning.py \
   --model_name meta-llama/Llama-3.2-1B \
   --num_epochs 1 \
   --dataset "custom_dataset" \
   --custom_dataset.file "custom_dataset.py" \
   --enable_fsdp \
   --use_peft \
   --peft_method lora \
   --output_dir ./output \
   --batch_size_training 1
```

I added
```python
    tokenizer.chat_template = DEFAULT_CHATML_CHAT_TEMPLATE
```
in the `get_custom_dataset` funtion, and it works, but I'm not sure if it's the right way

**Comment by HamidShojanazeri** [comment]
cc: @mreso

**Comment by HamidShojanazeri** [comment]
wonder if @Amerehei this would be helpful? https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/finetuning/datasets/custom_dataset.py#L22

**Comment by Amerehei** [comment]
Yes that's exactly what I have done. I used that file and changednto load my own dataset then I defined  `tokenizer.chat_template = DEFAULT_CHATML_CHAT_TEMPLATE` in the `get_custom_dataset` method

**Comment by mreso** [comment]
Hi @Amerehei yes, that will be the right approach here, as we're currently not providing any other point for users to alter the tokenizer. Please keep in mind that you're finetuning the base model which was not pretrained with a chat template (thats why there is non defined in the tokenizer). If you would finetune the Instruct variant meta-llama/Llama-3.2-1B-Instruct the tokenizer configuration will [already have the template](https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct/blob/main/tokenizer_config.json#L2053 ) as the model was pretrained with it. Closing this as you're solved you issue. Please feel free to reopen if there are any other questions related to this.
