### ISSUE TITLE
Long context

### ISSUE THREAD

**Issue by Amerehei** [meta-llama/llama-recipes#785]
When I increase `--context_length` no matter how many GPU is available, it ends with OutOfMemoryError error

I'm wondering why fully sharded FSDP doesn't work as expected

```
torchrun --nnodes 1 --nproc_per_node 8  recipes/quickstart/finetuning/finetuning.py --context_length 50000 --enable_fsdp --model_name /path_of_model_folder/8B --use_peft --peft_method lora --output_dir Path/to/save/PEFT/model --use_fast_kernels
```

How can I train a model with more than 50K context length

**Comment by wukaixingxp** [comment]
@Amerehei May I know what GPU you are using and how many GPU you have? The fine-tune needs a lot memory.. and 50K context needs insane amount of GPU memory, you can try to use [this GPU memory tool](https://rahulschand.github.io/gpu_poor/) to calculate.  BTW, our llama 3.1 model already supports 128K context length and you do not need to fine-tune to get that..

**Comment by Amerehei** [comment]
I tried with 8 x A40 each 48GB RAM
My problem is that, a single GPU can handle 5000 max token but with 8 of them I cannot increase it even it fails for 6000 tokens

**Comment by Amerehei** [comment]
And I want to use meta-llama/Llama-3.2-1B

**Comment by wukaixingxp** [comment]
what is your command? can you send me the error log?

**Comment by wukaixingxp** [comment]
Hi! FSDP is mostly used when a single model can not fit into a single GPU, and it will not increase the training context length. There is a [Context Parallel feature](https://github.com/pytorch/torchtitan/pull/592#top) that has been implemented by [Torchtitan](https://github.com/pytorch/torchtitan) where the context would be processed/parallelized and adding more GPU's would make an improvement. Hopefully, this can help with your problem.

**Comment by Amerehei** [comment]
@lessw2020 @wukaixingxp 
Thanks for the information
