### ISSUE TITLE
Unabled to load Finetuned Model

### ISSUE THREAD

**Issue by larawehbe** [meta-llama/llama-recipes#80]
### System Info

Hello 
I'm using Rocky Linux 9 

Torch and Transformers versions are complete as mentioned in the Readme file.

I cannot use the inference script in this case!!
this is the inference command  command

``` python3 inference/inference.py --model_name pretrained/ --prompt_file inference/samsum_prompt.txt  --use_auditnlg ``` 

i also tried to add this line 
```    torch.save(model.state_dict(), "pretrained/model.pth") ``` 
Then it resulted with this error 
```   raise EnvironmentError(
OSError: pretrained/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/pretrained//main' for available files. ``` 


Please i need your help
Thank you in advance 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug


i finetuned the model on alpaca dataset, and added the save pretrained flag as true in the configs of training.
this is the finetuning command
``` python3 llama_finetuning.py --use_peft --peft_method lora --quantization --model_name converted_7b --output_dir ./results --dataset alpaca_dataset  ``` 

It is saving only adapter_model.bin and adapter_config.json. only


### Error logs


I cannot use the inference script in this case!!
this is the inference command  command

``` python3 inference/inference.py --model_name pretrained/ --prompt_file inference/samsum_prompt.txt  --use_auditnlg ``` 

i also tried to add this line 
```    torch.save(model.state_dict(), "pretrained/model.pth") ``` 
Then it resulted with this error 
```   raise EnvironmentError(
OSError: pretrained/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/pretrained//main' for available files. ``` 



### Expected behavior

The expected behavior is either to save the model in a way that i can load it, either torch model (.pth ) or any other format maybe checkpoints so i can convert them, but the training only saves adapter bin and adapter config

**Comment by HamidShojanazeri** [comment]
@larawehbe

> adapter_model.bin and adapter_config.json

This is the PEFT module checkpoints, so this part is expected. 

The `model_name` should be path or name of the HF base model, like this like this[ 7B model](https://huggingface.co/meta-llama/Llama-2-7b-hf), can you pls make sure HF model exist/ have config.json in the ` pretrained/` folder.

**Comment by larawehbe** [comment]
> @larawehbe
> 
> > adapter_model.bin and adapter_config.json
> 
> This is the PEFT module checkpoints, so this part is expected.
> 
> The `model_name` should be path or name of the HF base model, like this like this[ 7B model](https://huggingface.co/meta-llama/Llama-2-7b-hf), can you pls make sure HF model exist/ have config.json in the ` pretrained/` folder.

The `pretrained`  folder doesnt include any config.json file, it only includes adapter bin and config. The `model_name` is a 7B llama2 model where i converted it to converted_7b file as stated in the readme file. 

now, I tried to convert it using `llama-recipes/inference/hf-text-generation-inference/merge_lora_weights.py` and it resulted in a  `merged` folder with the following files:

![image](https://github.com/facebookresearch/llama-recipes/assets/59616738/3beb5fff-74b1-4a9d-a282-84e79706a258)**

And it worked in this way, but the size is same as the size of the original model even after finetuning. Can i convert it to 4bit lora model ?

**Comment by HamidShojanazeri** [comment]
@larawehbe in the inference script you need to pass the PATH to the [base-model ](https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.py#L18)let say ` converted_7b` which should have the config.json which I assume is a HF checkpoint along with [PATH of the saved PEFT modules](https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.py#L19). You wont need to merge the weights, although that works as well.

**Comment by aaekay** [comment]
see, what fine tune does is produce a peft model/adapted model that is of small size and you have exported using quickstart guide.Now to make inference, you need peft model on the top of large pretrained model. so you pass two paths to inference script as followed:
model_name is path to hugging face model that is large pretrained model
peft_model  is path to the peft model you got from the quickstart guide after fine tuning

**Comment by timothylimyl** [comment]
@larawehbe @NiftyliuS 

If you are still unclear, you can look at what the `inference.py` is calling in `model_utils.py`, basically it calls:

```
# Function to load the main model for text generation
def load_model(model_name, quantization):
    model = LlamaForCausalLM.from_pretrained(
        model_name,
        return_dict=True,
        load_in_8bit=quantization,
        device_map="auto",
        low_cpu_mem_usage=True,
    )
    return model


# Function to load the PeftModel for performance optimization
def load_peft_model(model, peft_model):
    peft_model = PeftModel.from_pretrained(model, peft_model)
    return peft_model
```

Thus, if you finetuned using `--peft lora` you will get an adapter weights that needs to be merge into the original weights.  Put `--model_name` as the checkpoint path to the base weights and `--peft_model` as the path to your saved adapter folder (it will contain `adapter_config.json` and `adapter_model.bin`.

**Comment by HamidShojanazeri** [comment]
seems to be solved.
