### ISSUE TITLE
Can the meta-llama/Llama-3.2-1B-Instruct model be used for visual fine-tuning?

### ISSUE THREAD

**Issue by Sunstroperao** [meta-llama/llama-recipes#818]
### System Info

No

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

No

### Error logs

No

### Expected behavior

no

**Comment by IgorKasianenko** [comment]
As of today, the meta-llama/Llama-3.2-1B-Instruct model is not designed for visual fine-tuning. The Llama 3.2 Vision multimodal LLMs are pretrained and instruction-tuned image reasoning generative models in 11B and 90B sizes (text + images in / text out). Only two models are currently capable of handling visual inputs:
- Llama 3.2 Vision (11B)
- Llama 3.2 Vision (90B)

If you need to perform visual fine-tuning, we recommend using one of these two models.
