### ISSUE TITLE
How can I construct dataset for llama vision model

### ISSUE THREAD

**Issue by blurmemo** [meta-llama/llama-recipes#821]
I use my dataset for fine tuning, but I have a problem with dataset-construct.

I have a Q&A form dataset, I refer to alpaca_dataset.py method to write my_dataset.py.  In __getItem__(self, index) method, one of return result which is "**input_ids**" is the following sentence that will be processed by tokenizer.
**"Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:" + Answeer corresponding to Question
{instruction}: this is Question**

If I use the above format to construct my dataset for fine-tuning, can I use the fine-tuned model with input(Question and will be processed by chat template) to get a satisfactory answer?
**chat template** will process input to the following form.
**'<|start_header_id|>user<|end_header_id|>\n\n{input}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'**

I am very anxious for your help, thank you very much!

**Comment by wukaixingxp** [comment]
Hi! Please check out our [fine-tune recipe for vision model](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/finetuning/finetune_vision_model.md), you can follow the [ocrvqa example](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/finetuning/datasets/ocrvqa_dataset.py#L52) to write your own dataset. Let me know if you have any questions.

**Comment by blurmemo** [comment]
> Hi! Please check out our [fine-tune recipe for vision model](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/finetuning/finetune_vision_model.md), you can follow the [ocrvqa example](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/finetuning/datasets/ocrvqa_dataset.py#L52) to write your own dataset. Let me know if you have any questions.

Thank you for your help. I have solved this problem.
I choose the llama chat template to construct my dataset so that I can fine tune llama 3.2 **Instruct** vision model and infer with chat template.
[ocrvqa example](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/finetuning/datasets/ocrvqa_dataset.py#L52) is very helpful to me. Refer to this python file, I write my own dataset, sampler and collate_fn for Dataloader to satisfy my custom-dataset for fine-tuning.
