### ISSUE TITLE
LLaMA-3.1-8B_instruct eval config no filtering for MATH-HARD

### ISSUE THREAD

**Issue by wyzjack** [meta-llama/llama-recipes#824]
Thanks for the great repo! For the LLaMA-3.1-8B_instruct eval, 

https://github.com/meta-llama/llama-recipes/blob/ed87ba4abe97c16bb81833598f3bb793ff0e009f/tools/benchmarks/llm_eval_harness/meta_eval/meta_template/math_hard/math_hard_0shot_cot.yaml

Why there is not filter_list here to parse the answer?

I would appreciate it very much if you could reply. @aidando73 @wukaixingxp

**Comment by wukaixingxp** [comment]
@wyzjack We used process_results instead in [our yaml](https://github.com/meta-llama/llama-recipes/blob/ed87ba4abe97c16bb81833598f3bb793ff0e009f/tools/benchmarks/llm_eval_harness/meta_eval/meta_template/math_hard/math_hard_0shot_cot.yaml#L9) to parse the answer, please check [this function](https://github.com/meta-llama/llama-recipes/blob/ed87ba4abe97c16bb81833598f3bb793ff0e009f/tools/benchmarks/llm_eval_harness/meta_eval/meta_template/math_hard/utils.py#L38). Let me know if you have more questions!

**Comment by wyzjack** [comment]
Thanks very much for your reply which solves my problem. Congrats on the great work again!
