### ISSUE TITLE
Understanding FSDP Directory structure

### ISSUE THREAD

**Issue by kushalj001** [meta-llama/llama-recipes#83]
### System Info

Cuda version 11.8  
GPUs 2 A100  
torch 2.0.8 + cu118  

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### 🐛 Describe the bug

I have finetuned my model using only FSDP for 10 epochs. However, when I see the path for saved models, I only see the following two files, even though I save a checkpoint every epoch.

### Error logs

![image](https://github.com/facebookresearch/llama-recipes/assets/32245327/e3c6ca75-a6cf-405d-ba79-3f6b4c041895)

### Expected behavior

I want to know if these two files are the only expected outcomes of full fsdp finetuning for multiple epochs. Also how should I understand what these files actually refer to?

**Comment by HamidShojanazeri** [comment]
@kushalj001 these are distributed checkpoints with FSDP `SHARDED_STATED_DICT` which save one file per rank. You should get a `.metata` as the mapping file as well. If you pull the latest you will get all train +FSDP configs in `train_params.yaml` too. so, the _0_0.distc means the first file of rank 0 and so on.. Note, currently, we only keep save 1 checkpoints according to best eval.

<img width="226" alt="Screenshot 2023-08-01 at 5 17 08 PM" src="https://github.com/facebookresearch/llama-recipes/assets/9162336/d573f452-d82b-407a-9d39-3c2cc2db90ba">

**Comment by kushalj001** [comment]
Thanks for the reply, I have 2 follow ups:
* I don't have a `.metadata` file and `train_params.yaml` file in the directory. What could have caused this?
* Why is it not possible to have a checkpoint for each epoch? The best evals in my case happen in earlier epochs and I want the model to continue finetuning on my data.
Thanks

**Comment by dittops** [comment]
I also don't have the .metadata file. I'm using FULL_STATE_DICT for checkpoint_type.
