### ISSUE TITLE
Tensorboard/Wandb

### ISSUE THREAD

**Issue by zepmck** [meta-llama/llama-recipes#95]
### 🚀 The feature, motivation and pitch

Hi all!

Has anyone edited the code so to support logging on Tensorboard or WanDB?

Thanks!

**Comment by polym** [comment]
I tried to add wandb to llama-recipes training, but I'm not sure whether it's useful? 

Wandb web: https://wandb.ai/polym404/llama_recipes/workspace?workspace=user-polym404
PR: https://github.com/facebookresearch/llama-recipes/pull/200

@mreso could you give me some advice?

**Comment by HamidShojanazeri** [comment]
@polym its for sure useful in tracking your experiments, we are looking into adding some MLOP options.

**Comment by wukaixingxp** [comment]
Hi! The wandb feature has been integrated. Please check [here](https://github.com/meta-llama/llama-recipes/tree/main/recipes/finetuning#weights--biases-experiment-tracking) for more details
