### ISSUE TITLE
fp16 support for Single GPU fine tuning

### ISSUE THREAD

**Issue by NiftyliuS** [meta-llama/llama-recipes#99]
### 🚀 The feature, motivation and pitch

I am running 3090 with 24GB VRAM and 16GB Shared memory ( Total is 40 GB )
When i am fine tuning 7B model the original model scales up to 28GB which is the full float 32...

This introduces an issue - the moment any part of the training touches the Shared Memory the Iteration speed plumets significantly....

### Additional context

I tested on LLama 2 chat 13B with quanitize option enabled
when running batch size of 16 with alpaca_dataset it is using 22.7GB of Vram and i get ~7s per iteration and it ends up being roughly 8h per epoch
However
When i scale to 32 and it crosses the line of the VRAM i then get 6 days per epoch....

I get similar behavior using FSDP where 7B with `use_fp16=true` and `use_fp16=flase` require the same 28 GB of Vram ( 24 GPU and 3.9 Shared )

**Comment by HamidShojanazeri** [comment]
@NiftyliuS can you pls elaborate a bit more and clarify on the issue.  Are you seeing speed decrease along the training with PEFT+quantization and fp16 in FSDP?

**Comment by NiftyliuS** [comment]
@HamidShojanazeri the GPU i have shares part of my system RAM ( as Shared Memory ). 
So that puts me at 24GB VRAM + 16GB RAM totaling a 40GB that the GPU can use.

Note: i am running the finetune python script without torch wrapper - as described in the description

**I cant fit the 7B into 24GB VRAM** with the current llama_finetunin.py at all ( nothing changes the fact that it requires 28GB of memory ) so i cant attest for tuning speed difference there.

I do know that i can tune Quanitized version of 13B with 12-16 batch sizes. since it takes about 21-23 GB of VRAM
With that config Quantized 13B with Alpaca set takes 8-8.5H to do an epoch ( 7s per iteration ).

When i increase the batch sizes to 20 or more the time goes from 7s per iteration to ~100.

This is not a big surprise since GDDR6 is much much faster than DDR4..... my issue is the fact that i cant fit 7B on a 3090 when training but it does take 15GB Vram when inferencing


So no surprise wh

**Comment by NiftyliuS** [comment]
@HamidShojanazeri i ended up creating a single GPU cuda training version of the llama_finetuning.py
Do you want me to do a PR? i added explicit BF16 and FP16 support
+ a list of logs to actually see what the code is doing during the initialization proccess?

**Comment by HamidShojanazeri** [comment]
@NiftyliuS Thanks for updates, surely interested to look at your modifications and see if we can compose it with other supported modes in the repo. Please share a pointer/ PR to review.

**Comment by timothylimyl** [comment]
On the current script, single gpu bf16 seems to take more than 22GB, goes OOM on A5000.  Is it possible that the sequence length is causing this? I do not mind putting it to 2048, some pointers will be great.

```CUDA_VISIBLE_DEVICES=2 python llama_finetuning.py  --use_peft --peft_method lora  --m
odel_name /path/to/Llama-2-7b-hf/ --output_dir checkpoints/baseline_exp/lora --pure_bf16 --micro_batch_size 1```

**Comment by timothylimyl** [comment]
tried pointing to llama1 weights for 7B, same issue, goes OOM after it loads half way

**Comment by wukaixingxp** [comment]
Hi! We now supports` --quantization` to load weights in 8bit, [this tutorial](https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/singlegpu_finetuning.md#how-to-run-it) may help you to solve OOM
